/* PAPERFORGE S4 · LEGION II · part 3/6 — THERMO/STAT Q21-30
   Original items, authored+re-derived 2026-08-18. Schema as in pf2_p1.js. */
[
{id:'PF-TH-21',n:21,lane:'thermo',sub:'carnot',type:'MCQ',marks:1,diff:'seed',fig:'th-carnot-pv',
stem:'The figure shows a Carnot cycle drawn in the $P$–$V$ plane. The area enclosed by the loop equals, per cycle,',
opts:['the heat absorbed from the hot reservoir','the net work done by the gas','the entropy delivered to the cold reservoir','zero, because the cycle is reversible'],
ans:1,
sol:'$W=\\oint P\\,dV$ is literally the loop area. It is nonzero; reversibility is a statement about entropy generation, not about the enclosed area.',tags:['carnot','pv-diagram']},
{id:'PF-TH-22',n:22,lane:'thermo',sub:'entropy',type:'MCQ',marks:2,diff:'standard',
stem:'One mole of an ideal gas expands isothermally to twice its initial volume. The entropy change of the gas is',
opts:['$2.88\\,\\mathrm{J\\,K^{-1}}$','$5.76\\,\\mathrm{J\\,K^{-1}}$','$8.31\\,\\mathrm{J\\,K^{-1}}$','$11.53\\,\\mathrm{J\\,K^{-1}}$'],
ans:1,
sol:'$\\Delta S=nR\\ln(V_f/V_i)=R\\ln2=8.314\\times0.6931=5.76\\,\\mathrm{J\\,K^{-1}}$. The temperature ($300\\,\\mathrm{K}$ or any other) drops out of the result.',tags:['isothermal','entropy']},
{id:'PF-TH-23',n:23,lane:'thermo',sub:'radiation',type:'NAT',marks:2,diff:'standard',
stem:'Blackbody radiation fills an evacuated cavity held at $T=10^{4}\\,\\mathrm{K}$. Using the radiation constant $a=7.566\\times10^{-16}\\,\\mathrm{J\\,m^{-3}\\,K^{-4}}$, the radiation pressure on the cavity walls, in $\\mathrm{N\\,m^{-2}}$, is',
ans:'2.45 to 2.60',
sol:'$p=u/3=aT^4/3=7.566\\times10^{-16}\\times10^{16}/3=7.566/3=2.522\\,\\mathrm{N\\,m^{-2}}$. The factor $1/3$ is the photon equation of state.',tags:['blackbody','pressure']},
{id:'PF-TH-24',n:24,lane:'thermo',sub:'maxwell-relations',type:'MCQ',marks:1,diff:'standard',
stem:'Which Maxwell relation follows from the Gibbs free energy $G(T,P)$?',
opts:['$(\\partial S/\\partial P)_T=-(\\partial V/\\partial T)_P$','$(\\partial S/\\partial P)_T=(\\partial V/\\partial T)_P$','$(\\partial S/\\partial V)_T=(\\partial P/\\partial T)_V$','$(\\partial T/\\partial V)_S=-(\\partial P/\\partial S)_V$'],
ans:0,
sol:'From $dG=-S\\,dT+V\\,dP$, equality of mixed partials gives $(\\partial S/\\partial P)_T=-(\\partial V/\\partial T)_P$. The third option comes from the Helmholtz energy $F(T,V)$, the fourth from $U(S,V)$.',tags:['maxwell-relations']},
{id:'PF-TH-25',n:25,lane:'thermo',sub:'second-law',type:'MSQ',marks:2,diff:'standard',
stem:'Which statements is/are consistent with the second law of thermodynamics?',
opts:['No cyclic engine can convert heat drawn from a single reservoir entirely into work (Kelvin–Planck)','Heat cannot by itself flow from a colder body to a hotter one (Clausius)','The entropy of an isolated system never decreases','A Carnot engine working between two reservoirs can exceed the efficiency $1-T_c/T_h$'],
ans:[0,1,2],
sol:'The first three are the classic equivalent statements. Carnot efficiency is the universality bound; beating it would violate the second law.',tags:['second-law']},
{id:'PF-TH-26',n:26,lane:'thermo',sub:'fermi-gas',type:'MCQ',marks:2,diff:'standard',
stem:'For a three-dimensional free-electron gas, $E_F\\propto n^{2/3}$. If the electron number density is increased by a factor of $8$, the Fermi energy is multiplied by',
opts:['$2$','$4$','$8$','$16$'],
ans:1,
sol:'$E_F\\propto n^{2/3}$ gives the factor $8^{2/3}=4$. Squaring $k_F$ (which doubles) is the quick route to the same answer.',tags:['fermi-energy','scaling']},
{id:'PF-TH-27',n:27,lane:'thermo',sub:'einstein-solid',type:'NAT',marks:2,diff:'apex',
stem:'A monatomic Einstein solid contains one mole of atoms (three independent oscillators each) with $\\hbar\\omega/k_B=100\\,\\mathrm{K}$. At $T=300\\,\\mathrm{K}$, the molar heat capacity ratio $C_V/R$ is',
ans:'2.94 to 3.00',
sol:'$C_V=3R\\,x^2e^x/(e^x-1)^2$ with $x=100/300=1/3$: the Einstein factor is $0.9907$, so $C_V/R=3\\times0.9907=2.972$.',tags:['einstein-model','heat-capacity']},
{id:'PF-TH-28',n:28,lane:'thermo',sub:'two-level',type:'MCQ',marks:2,diff:'standard',
stem:'A two-level system has energies $0$ and $\\epsilon$. In thermal equilibrium at the temperature for which $\\epsilon/k_BT=1$, its mean energy is',
opts:['$0.269\\,\\epsilon$','$0.500\\,\\epsilon$','$0.731\\,\\epsilon$','$\\epsilon$'],
ans:0,
sol:'$Z=1+e^{-1}$ and $\\langle E\\rangle=\\epsilon e^{-1}/Z=\\epsilon/(e+1)=0.269\\,\\epsilon$. The distractors are the high-$T$ limit and $1-0.269$.',tags:['partition-function']},
{id:'PF-TH-29',n:29,lane:'thermo',sub:'gibbs-paradox',type:'MCQ',marks:1,diff:'standard',
stem:'The Gibbs paradox in the entropy of mixing is resolved within classical statistics by',
opts:['quantizing the allowed energy levels','dividing the phase-space volume by $N!$ for indistinguishable particles','including relativistic corrections to the dispersion relation','adding anharmonic corrections to the interaction potential'],
ans:1,
sol:'The $1/N!$ factor recognizes that permuting identical particles is not a new microstate; mixing identical gases then carries zero entropy change and extensivity is restored.',tags:['gibbs-paradox','correct-boltzmann-counting']},
{id:'PF-TH-30',n:30,lane:'thermo',sub:'phase-transitions',type:'MSQ',marks:2,diff:'apex',
stem:'Which statements about phase transitions is/are TRUE?',
opts:['A first-order transition absorbs or releases latent heat','At a continuous transition a response function (susceptibility) can diverge','Mean-field theory yields the order-parameter exponent $\\beta=\\tfrac12$','The two-dimensional Ising model on a square lattice has no finite-temperature phase transition'],
ans:[0,1,2],
sol:'Latent heat, diverging fluctuations and $\\beta=1/2$ are textbook results. Onsager’s exact solution gives the 2D Ising model a genuine ordering transition at finite $T_c$, so the last claim fails.',tags:['ising','critical-phenomena']}
]
