/* PAPERFORGE S4 · LEGION II · part 6/6 — ATOMIC/NUCLEAR Q51-52 + SOLID STATE Q53-60
   Original items, authored+re-derived 2026-08-18. Schema as in pf2_p1.js. */
[
{id:'PF-AN-51',n:51,lane:'atnuc',sub:'term-symbols',type:'MCQ',marks:2,diff:'apex',
stem:'By Hund rules, the ground term arising from the carbon configuration $1s^2\\,2s^2\\,2p^2$ is',
opts:['$^1S_0$','$^3P_0$','$^1D_2$','$^3D_1$'],
ans:1,
sol:'Maximize spin: $S=1$ (triplet). Within the Pauli limits for $p^2$, maximize $L$: $L=1$ ($P$). A less-than-half-filled subshell gives $J=|L-S|=0$, so $^3P_0$.',tags:['hund-rules','ls-coupling']},
{id:'PF-AN-52',n:52,lane:'atnuc',sub:'rydberg',type:'NAT',marks:1,diff:'standard',
stem:'Using the Rydberg constant $R_H=1.097\\times10^{7}\\,\\mathrm{m^{-1}}$, the wavelength of the Balmer-$\\alpha$ line of hydrogen ($n=3\\to n=2$), in nm, is',
ans:'654 to 658',
sol:'$1/\\lambda=R_H(1/4-1/9)=5R_H/36$, so $\\lambda=36/(5R_H)=36/(5.485\\times10^{7})=6.563\\times10^{-7}\\,\\mathrm{m}=656.3\\,\\mathrm{nm}$.',tags:['balmer-series']},
{id:'PF-SS-53',n:53,lane:'solidstate',sub:'crystal-structure',type:'MCQ',marks:1,diff:'seed',
stem:'The atomic packing fraction of the body-centred cubic (BCC) structure is',
opts:['$0.52$','$0.68$','$0.74$','$0.79$'],
ans:1,
sol:'Two atoms per cell touch along the body diagonal, $4r=\\sqrt{3}\\,a$: $f=\\frac{2\\cdot\\frac43\\pi r^3}{a^3}=\\frac{\\sqrt3\\,\\pi}{8}=0.68$. ($0.74$ is FCC; $0.52$ is simple cubic.)',tags:['packing-fraction']},
{id:'PF-SS-54',n:54,lane:'solidstate',sub:'diffraction',type:'MCQ',marks:2,diff:'standard',
stem:'X-rays of wavelength $1.54\\,\\text{\\AA}$ give a first-order Bragg reflection from a set of lattice planes at $\\theta=15^\\circ$. The interplanar spacing is closest to',
opts:['$1.49\\,\\text{\\AA}$','$2.97\\,\\text{\\AA}$','$5.95\\,\\text{\\AA}$','$0.77\\,\\text{\\AA}$'],
ans:1,
sol:'Bragg: $\\lambda=2d\\sin\\theta$, so $d=1.54/(2\\sin15^\\circ)=1.54/0.5176=2.97\\,\\text{\\AA}$.',tags:['bragg-law']},
{id:'PF-SS-55',n:55,lane:'solidstate',sub:'hall-effect',type:'NAT',marks:2,diff:'standard',
stem:'Copper has conduction-electron density $n=8.5\\times10^{28}\\,\\mathrm{m^{-3}}$. The magnitude of its Hall coefficient $R_H=1/(ne)$, in units of $10^{-11}\\,\\mathrm{m^3\\,C^{-1}}$, is',
ans:'7.2 to 7.5',
sol:'$R_H=1/(8.5\\times10^{28}\\times1.602\\times10^{-19})=1/(1.362\\times10^{10})=7.35\\times10^{-11}\\,\\mathrm{m^3\\,C^{-1}}$.',tags:['hall-coefficient']},
{id:'PF-SS-56',n:56,lane:'solidstate',sub:'band-theory',type:'MSQ',marks:2,diff:'standard',
stem:'Which statements of band theory is/are TRUE?',
opts:['a completely filled band carries no net current','the resistivity of an intrinsic semiconductor decreases as temperature rises','in an intrinsic semiconductor the electron and hole densities are equal','light doping changes the lattice constant of a semiconductor dramatically'],
ans:[0,1,2],
sol:'Filled-band states cancel in $\\pm k$ pairs; thermal activation across the gap lowers $\\rho(T)$; charge neutrality gives $n=p$ intrinsically. Dopants at parts-per-million leave the lattice essentially unchanged.',tags:['semiconductors']},
{id:'PF-SS-57',n:57,lane:'solidstate',sub:'superconductivity',type:'MCQ',marks:1,diff:'standard',
stem:'The Meissner effect in a superconductor is the',
opts:['vanishing of electrical resistance below $T_c$','expulsion of magnetic flux from the bulk below $T_c$','quantization of trapped flux in units of $h/e$','jump of the specific heat at $T_c$ with no latent heat'],
ans:1,
sol:'Meissner–Ochsenfeld: an applied field is actively expelled so $B=0$ in the bulk (type I, below $H_c$). Zero resistance alone would freeze flux in, not push it out.',tags:['meissner']},
{id:'PF-SS-58',n:58,lane:'solidstate',sub:'debye',type:'NAT',marks:2,diff:'seed',
stem:'In the low-temperature Debye regime a solid obeys $C_V=\\beta T^3$. If $C_V=0.040\\,\\mathrm{J\\,mol^{-1}\\,K^{-1}}$ at $T=2\\,\\mathrm{K}$, its value at $T=4\\,\\mathrm{K}$, in $\\mathrm{J\\,mol^{-1}\\,K^{-1}}$, is',
ans:'0.32',
sol:'$C_V\\propto T^3$ and $(4/2)^3=8$, so $C_V(4\\,\\mathrm{K})=8\\times0.040=0.32\\,\\mathrm{J\\,mol^{-1}\\,K^{-1}}$.',tags:['debye-t3']},
{id:'PF-SS-59',n:59,lane:'solidstate',sub:'fermi-surface',type:'MCQ',marks:2,diff:'standard',
stem:'For a three-dimensional free-electron gas with $n=8.5\\times10^{28}\\,\\mathrm{m^{-3}}$, the Fermi wavevector $k_F=(3\\pi^2n)^{1/3}$ is approximately',
opts:['$4.3\\times10^{9}\\,\\mathrm{m^{-1}}$','$1.36\\times10^{10}\\,\\mathrm{m^{-1}}$','$2.7\\times10^{10}\\,\\mathrm{m^{-1}}$','$8.5\\times10^{9}\\,\\mathrm{m^{-1}}$'],
ans:1,
sol:'$3\\pi^2n=29.61\\times8.5\\times10^{28}=2.517\\times10^{30}\\,\\mathrm{m^{-3}}$; the cube root gives $k_F=1.36\\times10^{10}\\,\\mathrm{m^{-1}}$.',tags:['fermi-wavevector']},
{id:'PF-SS-60',n:60,lane:'solidstate',sub:'crystal-structure',type:'NAT',marks:1,diff:'seed',
stem:'An FCC metal has lattice constant $a=4.05\\,\\text{\\AA}$. Its nearest-neighbour distance, in $\\text{\\AA}$, is',
ans:'2.84 to 2.88',
sol:'FCC atoms touch along a face diagonal: $d=a/\\sqrt2=4.05/1.4142=2.864\\,\\text{\\AA}$.',tags:['nearest-neighbour']}
]
