/* PAPERFORGE S4 · LEGION II · part 1/6 — QUANTUM Q1-10
   Original items, authored+re-derived 2026-08-18 (double-solve journal:
   _audit/paperforge/forge_journal_legion2.md). Clean strings only — no audit chatter.
   Schema: {id,n,lane,sub,type,marks,diff,stem,opts,ans,sol,tags}
   MCQ: ans=int index · MSQ: ans=sorted int array · NAT: ans=string */
[
{id:'PF-QM-01',n:1,lane:'quantum',sub:'square-well',type:'MCQ',marks:1,diff:'seed',fig:'qm-well-states',
stem:'The figure shows the lowest energy levels and wavefunctions of a particle in the infinite well $0<x<L$. For the state $n=2$, the expectation value $\\langle x\\rangle$ is',
opts:['$L/4$','$L/2$','$2L/3$','$3L/4$'],
ans:1,
sol:'$|\\psi_2|^2$ is symmetric about $x=L/2$, so $\\langle x\\rangle=L/2$ (true for every $n$). Direct check: $\\frac{2}{L}\\int_0^L x\\sin^2(2\\pi x/L)\\,dx=L/2$.',tags:['expectation-value','symmetry']},
{id:'PF-QM-02',n:2,lane:'quantum',sub:'operators',type:'MCQ',marks:1,diff:'seed',
stem:'The commutator $[\\hat{x},\\hat{p}^2]$ equals',
opts:['$i\\hbar\\hat{p}$','$2i\\hbar\\hat{p}$','$-2i\\hbar\\hat{p}$','$i\\hbar\\hat{p}^2$'],
ans:1,
sol:'$[x,p^2]=[x,p]\\,p+p\\,[x,p]=i\\hbar p+i\\hbar p=2i\\hbar p$. Only terms linear in $\\hat p$ survive.',tags:['commutator']},
{id:'PF-QM-03',n:3,lane:'quantum',sub:'hydrogen',type:'NAT',marks:1,diff:'standard',
stem:'A hydrogen atom makes the transition $n=3\\to n=1$. The energy of the emitted photon, in units of $13.6\\,\\mathrm{eV}$, is',
ans:'0.88 to 0.90',
sol:'$\\Delta E=13.6(1-1/9)=13.6\\times8/9=12.09\\,\\mathrm{eV}$, which is $0.889$ in units of $13.6\\,\\mathrm{eV}$.',tags:['bohr-levels']},
{id:'PF-QM-04',n:4,lane:'quantum',sub:'harmonic-oscillator',type:'MCQ',marks:2,diff:'standard',
stem:'For the ground state of the one-dimensional harmonic oscillator, the product $\\Delta x\\,\\Delta p$ equals',
opts:['$\\hbar/4$','$\\hbar/2$','$\\hbar$','$3\\hbar/2$'],
ans:1,
sol:'The Gaussian ground state saturates the Heisenberg bound: $\\Delta x=\\sqrt{\\hbar/(2m\\omega)}$, $\\Delta p=\\sqrt{m\\omega\\hbar/2}$, so $\\Delta x\\Delta p=\\hbar/2$.',tags:['uncertainty']},
{id:'PF-QM-05',n:5,lane:'quantum',sub:'hydrogen',type:'MCQ',marks:1,diff:'seed',
stem:'Ignoring spin, the degeneracy of the hydrogen-atom level with principal quantum number $n=3$ is',
opts:['$3$','$6$','$9$','$18$'],
ans:2,
sol:'$\\sum_{l=0}^{n-1}(2l+1)=n^2$. For $n=3$: $1+3+5=9$. The factor $2$ from spin is excluded by the question.',tags:['degeneracy']},
{id:'PF-QM-06',n:6,lane:'quantum',sub:'formalism',type:'MSQ',marks:2,diff:'standard',
stem:'For a bound stationary state $\\psi(x,t)=\\phi(x)\\,e^{-iEt/\\hbar}$ of a one-dimensional Hamiltonian, which of the following statements is/are TRUE?',
opts:['$\\langle p\\rangle=0$','The probability density $|\\psi|^2$ is time independent','$\\Delta E=0$','$\\langle x\\rangle$ must vanish'],
ans:[0,1,2],
sol:'For a discrete eigenstate $\\langle p\\rangle=m\\,d\\langle x\\rangle/dt=0$; the phase cancels in $|\\psi|^2$; an energy eigenstate has zero spread. $\\langle x\\rangle$ need not vanish, e.g. in an asymmetric well.',tags:['stationary-state']},
{id:'PF-QM-07',n:7,lane:'quantum',sub:'box-3d',type:'NAT',marks:1,diff:'standard',
stem:'A particle is confined to a cubical box of side $L$. The degeneracy of the level whose energy is $E=6\\,\\pi^2\\hbar^2/(2mL^2)$ is',
ans:'3',
sol:'With $E_0=\\pi^2\\hbar^2/(2mL^2)$, $E/E_0=n_x^2+n_y^2+n_z^2=6=4+1+1$, so $(n_x,n_y,n_z)$ is a permutation of $(2,1,1)$: exactly $3$ states.',tags:['degeneracy','3d-box']},
{id:'PF-QM-08',n:8,lane:'quantum',sub:'spin',type:'MCQ',marks:2,diff:'standard',
stem:'A spin-$\\frac{1}{2}$ particle is prepared in the eigenstate $|S_z;+\\rangle$. A measurement of $S_x$ yields $+\\hbar/2$ with probability',
opts:['$1/4$','$1/3$','$1/2$','$1$'],
ans:2,
sol:'$|+x\\rangle=(|+z\\rangle+|-z\\rangle)/\\sqrt{2}$, hence $P=|\\langle+x|+z\\rangle|^2=1/2$.',tags:['spin-half','measurement']},
{id:'PF-QM-09',n:9,lane:'quantum',sub:'harmonic-oscillator',type:'MCQ',marks:1,diff:'seed',
stem:'For the harmonic-oscillator ladder operators, the commutator $[\\hat{a},\\hat{a}^\\dagger]$ equals',
opts:['$0$','$1$','$-1$','$i\\hbar$'],
ans:1,
sol:'With $\\hat a=(m\\omega\\hat x+i\\hat p)/\\sqrt{2m\\omega\\hbar}$ and $[\\hat x,\\hat p]=i\\hbar$, direct expansion gives $[\\hat a,\\hat a^\\dagger]=1$.',tags:['ladder-operators']},
{id:'PF-QM-10',n:10,lane:'quantum',sub:'harmonic-oscillator',type:'NAT',marks:2,diff:'apex',
stem:'A harmonic oscillator with $\\hbar\\omega=1\\,\\mathrm{eV}$ is in the eigenstate $n=2$. The expectation value of its kinetic energy, in eV, is',
ans:'1.25',
sol:'Virial theorem for the oscillator: $\\langle T\\rangle=E_n/2=(n+\\tfrac12)\\hbar\\omega/2=(2.5\\,\\mathrm{eV})/2=1.25\\,\\mathrm{eV}$.',tags:['virial','kinetic-energy']}
]
