/* PAPERFORGE S4 · LEGION II · part 2/6 — QUANTUM Q11-20
   Original items, authored+re-derived 2026-08-18. Schema as in pf2_p1.js. */
[
{id:'PF-QM-11',n:11,lane:'quantum',sub:'de-broglie',type:'MCQ',marks:2,diff:'standard',
stem:'An electron is accelerated from rest through a potential difference of $100\\,\\mathrm{V}$. Its de Broglie wavelength is approximately',
opts:['$0.0123\\,\\mathrm{nm}$','$0.123\\,\\mathrm{nm}$','$1.23\\,\\mathrm{nm}$','$12.3\\,\\mathrm{nm}$'],
ans:1,
sol:'$\\lambda=h/\\sqrt{2meV}=12.27/\\sqrt{V}$ in angstrom, so $\\lambda=12.27/10\\,\\text{\\AA}=0.123\\,\\mathrm{nm}$.',tags:['de-broglie']},
{id:'PF-QM-12',n:12,lane:'quantum',sub:'tunneling',type:'MCQ',marks:2,diff:'standard',
stem:'A particle with $E<V_0$ crosses a rectangular barrier of width $a$ with transmission $T\\approx e^{-2\\kappa a}$, $\\kappa=\\sqrt{2m(V_0-E)}/\\hbar$. If the barrier width is doubled (everything else unchanged), the transmission becomes approximately',
opts:['$T/2$','$T^2$','$2T$','$\\sqrt{T}$'],
ans:1,
sol:'$T(a)\\sim e^{-2\\kappa a}$ so $T(2a)=e^{-4\\kappa a}=T^2$: tunneling probability is exponentially sensitive to width.',tags:['tunneling','wkb']},
{id:'PF-QM-13',n:13,lane:'quantum',sub:'formalism',type:'MSQ',marks:2,diff:'standard',
stem:'Which statements about a Hermitian operator $\\hat{A}$ on a finite-dimensional Hilbert space is/are TRUE?',
opts:['All eigenvalues of $\\hat{A}$ are real','Eigenvectors belonging to distinct eigenvalues are orthogonal','The eigenvectors of $\\hat{A}$ can be chosen as a complete orthonormal basis','$\\hat{A}\\hat{B}$ is Hermitian for every Hermitian $\\hat{B}$'],
ans:[0,1,2],
sol:'The spectral theorem gives the first three. The product fails in general: $(AB)^\\dagger=BA\\neq AB$ unless $A$ and $B$ commute.',tags:['hermitian','spectral-theorem']},
{id:'PF-QM-14',n:14,lane:'quantum',sub:'hydrogen',type:'NAT',marks:2,diff:'standard',
stem:'For the hydrogen ground state ($1s$ orbital), the ratio $\\langle r\\rangle/a_0$ equals',
ans:'1.5',
sol:'With $\\psi_{1s}=(\\pi a_0^3)^{-1/2}e^{-r/a_0}$: $\\langle r\\rangle=\\int_0^\\infty 4\\pi r^3|\\psi_{1s}|^2\\,dr=\\frac{3}{2}a_0$, so the ratio is $1.5$.',tags:['expectation-value','hydrogen-1s']},
{id:'PF-QM-15',n:15,lane:'quantum',sub:'perturbation',type:'MCQ',marks:2,diff:'apex',
stem:'A particle sits in the ground state of the infinite well $0<x<L$. A weak perturbation $H^{\\prime}=\\epsilon\\,\\delta(x-L/2)$ is switched on. The first-order shift of the ground-state energy is',
opts:['$\\epsilon/L$','$2\\epsilon/L$','$\\epsilon/(2L)$','$0$'],
ans:1,
sol:'$\\Delta E^{(1)}=\\langle 1|H^{\\prime}|1\\rangle=\\epsilon\\,|\\psi_1(L/2)|^2=\\epsilon\\cdot\\frac{2}{L}\\sin^2(\\pi/2)=2\\epsilon/L$.',tags:['first-order-shift']},
{id:'PF-QM-16',n:16,lane:'quantum',sub:'identical-particles',type:'MCQ',marks:2,diff:'apex',
stem:'Two non-interacting identical spin-$\\frac{1}{2}$ fermions are placed in the infinite well $0<x<L$; let $E_1=\\pi^2\\hbar^2/(2mL^2)$ be the one-particle ground energy. The ground-state energy of the two-fermion system is',
opts:['$E_1$','$2E_1$','$3E_1$','$4E_1$'],
ans:1,
sol:'The spin singlet lets both fermions occupy $n=1$ with an antisymmetric spin state, giving $E=2E_1$. Forcing antisymmetry in space would push one particle to $n=2$, costing $5E_1$.',tags:['fermions','pauli']},
{id:'PF-QM-17',n:17,lane:'quantum',sub:'symmetry',type:'MSQ',marks:2,diff:'standard',
stem:'For the Hamiltonian $H=\\hat{p}^2/2m+V(r)$ with a central potential $V(r)$ and no spin-orbit coupling, which quantities is/are constants of motion?',
opts:['Every component $L_i$ of orbital angular momentum','$\\hat{L}^2$','Parity','The linear-momentum component $p_x$'],
ans:[0,1,2],
sol:'Rotational invariance gives $[H,L_i]=[H,L^2]=0$, and $V(r)$ is parity-even. Translation invariance is broken by $V(r)$, so $p_x$ is not conserved.',tags:['conservation-laws']},
{id:'PF-QM-18',n:18,lane:'quantum',sub:'square-well',type:'NAT',marks:2,diff:'standard',
stem:'A particle in the infinite well $0<x<L$ occupies the state $n=1$. The probability of finding it in the middle half of the well, $L/4<x<3L/4$, is',
ans:'0.80 to 0.83',
sol:'$P=\\frac{2}{L}\\int_{L/4}^{3L/4}\\sin^2(\\pi x/L)\\,dx=\\tfrac12+\\tfrac{1}{\\pi}\\sin(\\pi/2)=0.5+0.3183=0.8183$.',tags:['probability-density']},
{id:'PF-QM-19',n:19,lane:'quantum',sub:'selection-rules',type:'MCQ',marks:1,diff:'seed',
stem:'Which hydrogen-atom transition is allowed as an electric-dipole ($E1$) transition?',
opts:['$2s\\to1s$','$2p\\to1s$','$3d\\to2s$','$1s\\to1s$'],
ans:1,
sol:'$E1$ requires $\\Delta l=\\pm1$ (with parity change). Only $2p\\to1s$ has $\\Delta l=-1$; the others violate the rule.',tags:['dipole-transition']},
{id:'PF-QM-20',n:20,lane:'quantum',sub:'spin',type:'MCQ',marks:2,diff:'apex',
stem:'A spin-$\\frac{1}{2}$ particle of gyromagnetic ratio $\\gamma$ sits in a static field $B\\hat{z}$, initialized in $|S_x;+\\rangle$; write $\\omega=\\gamma B$. At time $t=\\pi/(2\\omega)$, an $S_x$ measurement again yields $+\\hbar/2$ with probability',
opts:['$1$','$1/2$','$1/4$','$0$'],
ans:1,
sol:'The spin precesses in the $xy$-plane; the return probability is $P=\\cos^2(\\omega t/2)=\\cos^2(\\pi/4)=1/2$.',tags:['larmor-precession']}
]
