/* PAPERFORGE S4 · LEGION II · part 4/6 — THERMO Q31-34 + ELECTRONICS Q35-40
   Original items, authored+re-derived 2026-08-18. Schema as in pf2_p1.js. */
[
{id:'PF-TH-31',n:31,lane:'thermo',sub:'van-der-waals',type:'NAT',marks:2,diff:'standard',
stem:'A van der Waals gas has $a=0.364\\,\\mathrm{Pa\\,m^6\\,mol^{-2}}$ and $b=4.27\\times10^{-5}\\,\\mathrm{m^3\\,mol^{-1}}$. Its critical temperature $T_c=8a/(27Rb)$, in kelvin, is',
ans:'301 to 306',
sol:'$T_c=8\\times0.364/(27\\times8.314\\times4.27\\times10^{-5})=2.912/9.585\\times10^{3}=303.8\\,\\mathrm{K}$.',tags:['critical-point']},
{id:'PF-TH-32',n:32,lane:'thermo',sub:'maxwell-distribution',type:'MCQ',marks:1,diff:'seed',
stem:'An ideal Maxwell gas is heated so that its absolute temperature quadruples. The most probable speed $v_p=\\sqrt{2k_BT/m}$ is multiplied by',
opts:['$\\sqrt{2}$','$2$','$4$','$16$'],
ans:1,
sol:'$v_p\\propto\\sqrt{T}$, and $\\sqrt{4}=2$. The same factor applies to $\\bar v$ and $v_{rms}$ by the common $\\sqrt{T}$ scaling.',tags:['speed-distribution']},
{id:'PF-TH-33',n:33,lane:'thermo',sub:'equipartition',type:'NAT',marks:1,diff:'standard',
stem:'Using $k_B=8.617\\times10^{-2}\\,\\mathrm{meV\\,K^{-1}}$, the mean translational kinetic energy per molecule of a monatomic ideal gas at $T=300\\,\\mathrm{K}$, in meV, is',
ans:'38.3 to 39.3',
sol:'$\\langle K\\rangle=\\tfrac32 k_BT=1.5\\times8.617\\times10^{-2}\\times300=38.78\\,\\mathrm{meV}$.',tags:['equipartition']},
{id:'PF-TH-34',n:34,lane:'thermo',sub:'free-expansion',type:'MCQ',marks:2,diff:'standard',
stem:'An ideal gas undergoes free (Joule) expansion into an evacuated chamber, doubling its volume. Regarding its temperature, the gas',
opts:['cools, because it pushes back the vacuum','shows zero temperature change','warms, because its entropy rises','oscillates in temperature until equilibrium sets in'],
ans:1,
sol:'Against vacuum $W=0$, and with insulating walls $Q=0$, so $\\Delta U=0$; for an ideal gas $U$ depends only on $T$, hence $\\Delta T=0$ while $\\Delta S=nR\\ln2>0$.',tags:['joule-expansion']},
{id:'PF-EL-35',n:35,lane:'electronics',sub:'opamp',type:'MCQ',marks:1,diff:'seed',
stem:'An ideal op-amp in a negative-feedback amplifier is analyzed using which pair of rules?',
opts:['the inputs draw no current, and feedback forces the two input voltages equal','the inputs draw no current, and the output is always saturated','the two inputs are joined by a real short, and the gain is infinite at all frequencies','the output current is zero, and the open-loop gain is zero'],
ans:0,
sol:'Golden rules: $i_+=i_-=0$, and negative feedback enforces the virtual short $v_+=v_-$. Saturation is a failure mode, not an analysis rule.',tags:['golden-rules']},
{id:'PF-EL-36',n:36,lane:'electronics',sub:'opamp',type:'MCQ',marks:2,diff:'standard',fig:'el-opamp-inverting',
stem:'In the inverting amplifier of the figure, $R_{in}=10\\,\\mathrm{k\\Omega}$ and $R_f=100\\,\\mathrm{k\\Omega}$. With $v_{in}=+0.5\\,\\mathrm{V}$, the output $v_{out}$ is',
opts:['$-5\\,\\mathrm{V}$','$+5\\,\\mathrm{V}$','$-0.05\\,\\mathrm{V}$','$+50\\,\\mathrm{V}$'],
ans:0,
sol:'Virtual earth at the inverting node: $v_{out}=-(R_f/R_{in})\\,v_{in}=-10\\times0.5=-5\\,\\mathrm{V}$. The sign flip is what makes the amplifier inverting.',tags:['inverting-amplifier']},
{id:'PF-EL-37',n:37,lane:'electronics',sub:'filters',type:'NAT',marks:2,diff:'standard',
stem:'A first-order $RC$ low-pass filter uses $R=1.59\\,\\mathrm{k\\Omega}$ and $C=100\\,\\mathrm{nF}$. Its $-3\\,\\mathrm{dB}$ cutoff frequency, in Hz, is',
ans:'990 to 1012',
sol:'$f_c=1/(2\\pi RC)=1/(2\\pi\\times1590\\times10^{-7})=1001\\,\\mathrm{Hz}$.',tags:['cutoff-frequency']},
{id:'PF-EL-38',n:38,lane:'electronics',sub:'diode',type:'MCQ',marks:1,diff:'seed',
stem:'A silicon diode (forward drop $0.7\\,\\mathrm{V}$) is wired in series with a $1\\,\\mathrm{k\\Omega}$ resistor across a $5\\,\\mathrm{V}$ supply. The forward current is approximately',
opts:['$4.3\\,\\mathrm{mA}$','$5.0\\,\\mathrm{mA}$','$4.3\\,\\mu\\mathrm{A}$','$0.7\\,\\mathrm{mA}$'],
ans:0,
sol:'$I=(5-0.7)/(1\\,\\mathrm{k\\Omega})=4.3\\,\\mathrm{mA}$. Ignoring the diode drop (the $5.0\\,\\mathrm{mA}$ answer) overstates the current.',tags:['diode-circuit']},
{id:'PF-EL-39',n:39,lane:'electronics',sub:'bjt',type:'MCQ',marks:2,diff:'standard',
stem:'An $npn$ transistor biased in the active region has $\\beta=100$ and base current $I_B=20\\,\\mu\\mathrm{A}$. Its collector current is',
opts:['$0.2\\,\\mathrm{mA}$','$2\\,\\mathrm{mA}$','$20\\,\\mathrm{mA}$','$200\\,\\mathrm{mA}$'],
ans:1,
sol:'$I_C=\\beta I_B=100\\times20\\,\\mu\\mathrm{A}=2\\,\\mathrm{mA}$, valid while the collector junction stays reverse biased (active region).',tags:['current-gain']},
{id:'PF-EL-40',n:40,lane:'electronics',sub:'feedback',type:'MSQ',marks:2,diff:'apex',
stem:'A voltage amplifier employs series-derived negative feedback with loop gain much larger than one. Which effects of the feedback is/are expected?',
opts:['the closed-loop gain is stabilized against device-parameter spread','the input impedance of the amplifier is increased','the amplifier bandwidth is extended','harmonic distortion is increased'],
ans:[0,1,2],
sol:'Negative feedback buys stability, raises input impedance for series mixing, and stretches bandwidth by the loop gain; distortion is reduced, not increased.',tags:['negative-feedback']}
]
