/* PAPERFORGE S4 · LEGION II · part 5/6 — ELECTRONICS Q41-44 + ATOMIC/NUCLEAR Q45-50
   Original items, authored+re-derived 2026-08-18. Schema as in pf2_p1.js. */
[
{id:'PF-EL-41',n:41,lane:'electronics',sub:'timer-555',type:'NAT',marks:2,diff:'standard',
stem:'A 555 timer in astable mode uses $R_A=R_B=10\\,\\mathrm{k\\Omega}$ and $C=10\\,\\mathrm{nF}$. Its oscillation frequency $f=1.44/[(R_A+2R_B)\\,C]$, in Hz, is',
ans:'4750 to 4850',
sol:'$R_A+2R_B=3\\times10^{4}\\,\\Omega$, so $f=1.44/(3\\times10^{4}\\times10^{-8})=1.44/(3\\times10^{-4})=4800\\,\\mathrm{Hz}$.',tags:['astable-multivibrator']},
{id:'PF-EL-42',n:42,lane:'electronics',sub:'zener',type:'MCQ',marks:2,diff:'standard',
stem:'A $12\\,\\mathrm{V}$ source feeds a $5.6\\,\\mathrm{V}$ Zener regulator through a series resistor $R_s=320\\,\\Omega$. The load across the Zener draws $10\\,\\mathrm{mA}$. The Zener current is',
opts:['$0\\,\\mathrm{mA}$','$10\\,\\mathrm{mA}$','$20\\,\\mathrm{mA}$','$30\\,\\mathrm{mA}$'],
ans:1,
sol:'Series current $I_s=(12-5.6)/320=20\\,\\mathrm{mA}$; after supplying the $10\\,\\mathrm{mA}$ load the Zener carries $I_Z=20-10=10\\,\\mathrm{mA}$.',tags:['voltage-regulator']},
{id:'PF-EL-43',n:43,lane:'electronics',sub:'digital',type:'MCQ',marks:1,diff:'seed',
stem:'The output of a two-input XOR gate is HIGH precisely when',
opts:['both inputs are LOW','the two inputs differ','both inputs are HIGH','at least one input is HIGH'],
ans:1,
sol:'$Y=A\\bar{B}+\\bar{A}B$: the output is $1$ only for the mixed input pairs $(0,1)$ and $(1,0)$. The last option describes OR, not XOR.',tags:['logic-gates']},
{id:'PF-EL-44',n:44,lane:'electronics',sub:'digital',type:'NAT',marks:1,diff:'seed',
stem:'The decimal value of the binary number $1011_2$ is',
ans:'11',
sol:'$1011_2=1\\times8+0\\times4+1\\times2+1\\times1=11$.',tags:['number-systems']},
{id:'PF-AN-45',n:45,lane:'atnuc',sub:'zeeman',type:'MCQ',marks:1,diff:'standard',fig:'am-zeeman-triplet',
stem:'The figure sketches the normal Zeeman effect for the spectral line $^1P_1\\to{}^1S_0$. In a weak magnetic field, into how many components does this line split?',
opts:['$1$','$2$','$3$','$5$'],
ans:2,
sol:'Selection rule $\\Delta m_J=0,\\pm1$ with equal level splitting $g_J\\mu_BB$ collapses the fan into three equispaced lines ($\\pi$, $\\sigma^+$, $\\sigma^-$): a triplet, as the figure shows.',tags:['zeeman-effect']},
{id:'PF-AN-46',n:46,lane:'atnuc',sub:'moseley',type:'MCQ',marks:2,diff:'standard',
stem:'By Moseley law the $K\\alpha$ frequency scales as $\\nu\\propto(Z-1)^2$. Moving the target from aluminium ($Z=13$) to manganese ($Z=25$) multiplies the $K\\alpha$ frequency by',
opts:['$2$','$4$','$8$','$16$'],
ans:1,
sol:'Ratio $=(25-1)^2/(13-1)^2=(24/12)^2=2^2=4$.',tags:['x-ray-spectra']},
{id:'PF-AN-47',n:47,lane:'atnuc',sub:'radioactivity',type:'NAT',marks:2,diff:'seed',
stem:'A radioactive sample has a half-life of $5$ days. The fraction of the original nuclei remaining after $15$ days is',
ans:'0.125',
sol:'Fifteen days is three half-lives: $N/N_0=(1/2)^3=1/8=0.125$.',tags:['half-life']},
{id:'PF-AN-48',n:48,lane:'atnuc',sub:'nuclear-structure',type:'MSQ',marks:2,diff:'apex',
stem:'Which statements about nuclear structure and decay is/are TRUE?',
opts:['the strong nuclear force is short-ranged','saturation of the binding energy per nucleon indicates each nucleon binds only to its near neighbours','the semi-empirical mass formula by itself explains the magic numbers','in $\\beta^-$ decay a neutron converts to a proton, emitting an electron and an antineutrino'],
ans:[0,1,3],
sol:'Short range and saturation are the force hallmarks, and $\\beta^-$ is $n\\to p+e^-+\\bar\\nu_e$. Magic numbers require the shell model; the smooth SEMF cannot generate them.',tags:['semf','beta-decay']},
{id:'PF-AN-49',n:49,lane:'atnuc',sub:'angular-momentum',type:'MCQ',marks:1,diff:'standard',
stem:'The number of $m_j$ sublevels of the atomic level $2P_{3/2}$ is',
opts:['$2$','$3$','$4$','$6$'],
ans:2,
sol:'Degeneracy $=2j+1$; with $j=3/2$ this is $4$. Spin-orbit splits $2P$ into $j=1/2$ (twofold) and $j=3/2$ (fourfold).',tags:['fine-structure']},
{id:'PF-AN-50',n:50,lane:'atnuc',sub:'alpha-decay',type:'MCQ',marks:2,diff:'standard',
stem:'Given $M(^{238}\\mathrm{U})=238.0508\\,u$, $M(^{234}\\mathrm{Th})=234.0436\\,u$ and $M(^4\\mathrm{He})=4.0026\\,u$, with $1\\,u=931.5\\,\\mathrm{MeV}/c^2$, the $Q$ value of $^{238}\\mathrm{U}\\to{}^{234}\\mathrm{Th}+\\alpha$ is',
opts:['$0.43\\,\\mathrm{MeV}$','$4.28\\,\\mathrm{MeV}$','$42.8\\,\\mathrm{MeV}$','$0.93\\,\\mathrm{MeV}$'],
ans:1,
sol:'$Q=(238.0508-234.0436-4.0026)\\,u\\times931.5=0.0046\\times931.5=4.28\\,\\mathrm{MeV}$.',tags:['q-value']}
]
