/* PAPERFORGE S3 · LEGION I · part 6/6 — ELECTROMAGNETIC THEORY Q51-60 */
[
{id:'PF-EM-51',n:51,lane:'emtheory',sub:'maxwell',type:'MSQ',marks:2,diff:'standard',
stem:'At the interface between two dielectric media, with NO free surface charge and NO free surface current, which quantities are continuous across the boundary?',
opts:['Tangential component of $\\mathbf{E}$','Normal component of $\\mathbf{D}$','Normal component of $\\mathbf{B}$','Tangential component of $\\mathbf{E}$ is NOT continuous'],
ans:[0,1,2],
sol:'$\\nabla\\times\\mathbf E=0$ (electrostatic regime) ⇒ $E_{\\|}$ continuous ✓. $\\nabla\\cdot\\mathbf D=\\rho_f$: no free surface charge ⇒ $D_\\perp$ continuous ✓. $\\nabla\\cdot\\mathbf B=0$ always ⇒ $B_\\perp$ continuous ✓. (D asserts the false converse.)',tags:['boundary-conditions','interfaces']},
{id:'PF-EM-52',n:52,lane:'emtheory',sub:'waves',type:'MCQ',marks:2,diff:'apex',
stem:'The skin depth in copper ($\\sigma=5.8\\times10^{7}$ S/m, $\\mu\\approx\\mu_{0}$) at $f=1$ MHz is closest to',
opts:['$6.6\\,\\mu$m','$66\\,\\mu$m','$660\\,\\mu$m','$0.66\\,\\mu$m'],
ans:1,
sol:'$\\delta=\\sqrt{\\dfrac{2}{\\mu_0\\sigma\\omega}}=\\sqrt{\\dfrac{2}{(4\\pi\\times10^{-7})(5.8\\times10^{7})(2\\pi\\times10^{6})}}=\\sqrt{\\dfrac{2}{4.579\\times10^{8}}}=6.6\\times10^{-5}$ m $=66\\,\\mu$m.',tags:['skin-depth','good-conductor']},
{id:'PF-EM-53',n:53,lane:'emtheory',sub:'waves',type:'NAT',marks:2,diff:'standard',
stem:'A plane wave in vacuum has peak field $E_{0}=60$ V/m. Report its average intensity (power per unit area) in W/m$^{2}$ (2 d.p.).',
ans:'4.76 to 4.79',
sol:'$\\langle S\\rangle=\\dfrac{E_0^{2}}{2\\mu_0 c}=\\dfrac{3600}{2\\times(4\\pi\\times10^{-7})\\times3\\times10^{8}}=\\dfrac{3600}{753.98}=4.77$ W/m$^{2}$.',tags:['poynting','intensity']},
{id:'PF-EM-54',n:54,lane:'emtheory',sub:'waves',type:'MCQ',marks:2,diff:'apex',
stem:'A rectangular waveguide has broad dimension $a=2$ cm. The cutoff frequency of the dominant TE$_{10}$ mode is',
opts:['$5.0$ GHz','$7.5$ GHz','$15.0$ GHz','$3.75$ GHz'],
ans:1,
sol:'$f_c=\\dfrac{c}{2a}=\\dfrac{3\\times10^{8}}{2\\times0.02}=7.5\\times10^{9}$ Hz $=7.5$ GHz.',tags:['waveguide','cutoff']},
{id:'PF-EM-55',n:55,lane:'emtheory',sub:'dielectrics',type:'MCQ',marks:2,diff:'standard',
stem:'A parallel-plate capacitor (plate area $A$, separation $d$, empty capacitance $C_{0}=\\varepsilon_{0}A/d$) has a dielectric slab of constant $\\kappa=3$ and thickness $d/2$ inserted parallel to the plates. The new capacitance is',
opts:['$C_{0}$','$1.5\\,C_{0}$','$2\\,C_{0}$','$3\\,C_{0}$'],
ans:1,
sol:'Series combination: air gap $d/2$ ($C=2C_0$) and dielectric slab ($C=2\\kappa C_0=6C_0$): $C=\\dfrac{(2C_0)(6C_0)}{2C_0+6C_0}=\\dfrac{12}{8}C_0=1.5\\,C_0$. (General: $C=\\tfrac{2\\kappa}{1+\\kappa}C_0$.)',tags:['dielectric-slab','series-capacitance']},
{id:'PF-EM-56',n:56,lane:'emtheory',sub:'electrostatics',type:'NAT',marks:1,diff:'standard',
stem:'Air breaks down at about $E=3\\times10^{6}$ V/m. Report the electrostatic energy density (J/m$^{3}$) at this field (1 d.p.).',
ans:'39.5 to 40.1',
sol:'$u=\\tfrac12\\varepsilon_0 E^{2}=\\tfrac12\\times8.854\\times10^{-12}\\times9\\times10^{12}=\\tfrac12\\times79.7=39.8$ J/m$^{3}$.',tags:['energy-density','electrostatics']},
{id:'PF-EM-57',n:57,lane:'emtheory',sub:'electrostatics',type:'MCQ',marks:1,diff:'seed',
stem:'Far from an electric dipole, the ratio of the equatorial field magnitude to the axial field magnitude (at the same distance) is',
opts:['$\\dfrac12$','$2$','$1$','$\\dfrac14$'],
ans:0,
sol:'$E_{\\rm axial}=\\dfrac{2p}{4\\pi\\varepsilon_0 r^{3}}$, $E_{\\rm equat}=\\dfrac{p}{4\\pi\\varepsilon_0 r^{3}}$ ⇒ ratio $=\\tfrac12$.',tags:['dipole-field','scaling']},
{id:'PF-EM-58',n:58,lane:'emtheory',sub:'electrostatics',type:'MCQ',marks:2,diff:'apex',
stem:'A point charge $q$ is placed at distance $a>R$ from the centre of a grounded conducting sphere of radius $R$. The image charge is located at distance (from the centre)',
opts:['$\\dfrac{R}{a}$','$\\dfrac{R^{2}}{a}$','$\\dfrac{a}{R}$','$\\dfrac{a^{2}}{R}$'],
ans:1,
sol:'Standard result: image $q^{\\prime}=-qR/a$ sits at $b=R^{2}/a$ on the radial line to the charge. Check limits: $a\\to R^{+}$ gives $b\\to R^{-}$ (image meets surface) ✓',tags:['image-charges','sphere']},
{id:'PF-EM-59',n:59,lane:'emtheory',sub:'magnetostatics',type:'MCQ',marks:2,diff:'standard',
stem:'Two long parallel wires a distance $d$ apart each carry current $I$ in the SAME direction. The force per unit length between them is',
opts:['$\\dfrac{\\mu_{0}I^{2}}{2\\pi d}$, attractive','$\\dfrac{\\mu_{0}I^{2}}{2\\pi d}$, repulsive','$\\dfrac{\\mu_{0}I^{2}}{4\\pi d}$, attractive','$\\dfrac{\\mu_{0}I^{2}}{4\\pi d^{2}}$, attractive'],
ans:0,
sol:'Wire 2 sits in $B=\\mu_0 I/(2\\pi d)$ of wire 1: $F/\\ell=IB=\\mu_0 I^{2}/(2\\pi d)$; parallel currents attract (right-hand rule + $\\mathbf I\\ell\\times\\mathbf B$ direction).',tags:['force-between-wires','ampere']},
{id:'PF-EM-60',n:60,lane:'emtheory',sub:'magnetostatics',type:'NAT',marks:2,diff:'apex',
stem:'For a uniform field $\\mathbf B=B_{0}\\hat{z}$, one may choose the symmetric-gauge vector potential $\\mathbf A=\\tfrac{1}{2}\\mathbf B\\times\\mathbf r$. With $B_{0}=0.5$ T, evaluate $|\\mathbf A|$ at the point $(x,y,z)=(0.4,\\,0,\\,7)$ m, in T·m (2 d.p.).',
ans:'0.1',
sol:'$|\\mathbf A|=\\tfrac12 B_{0}r_{\\perp}$ where $r_{\\perp}=\\sqrt{x^{2}+y^{2}}=0.4$ m (z is along $\\mathbf B$, does not enter): $|\\mathbf A|=\\tfrac12\\times0.5\\times0.4=0.1$ T·m. Check: symmetries of uniform $B$ respected ✓',tags:['vector-potential','gauge']},
]
