/* PAPERFORGE S3 · LEGION I · part 3/6 — CLASSICAL MECHANICS Q21-30 */
[
{id:'PF-CM-21',n:21,lane:'classical',sub:'newtonian',type:'MCQ',marks:1,diff:'seed',
stem:'An ideal Atwood machine carries masses $m$ and $3m$ over a massless frictionless pulley. The acceleration of the system is',
opts:['$\\dfrac{g}{3}$','$\\dfrac{g}{2}$','$\\dfrac{2g}{3}$','$\\dfrac{3g}{4}$'],
ans:1,
sol:'$a=\\dfrac{(3m-m)g}{3m+m}=\\dfrac{2}{4}g=\\dfrac{g}{2}$.',tags:['atwood','newton-second']},
{id:'PF-CM-22',n:22,lane:'classical',sub:'newtonian',type:'NAT',marks:1,diff:'standard',
stem:'A projectile is launched at $v=20$ m/s at $\\theta=30^{\\circ}$ on level ground. Using $g=10$ m/s$^{2}$, report the range in metres (2 d.p.).',
ans:'34.63 to 34.66',
sol:'$R=\\dfrac{v^{2}\\sin2\\theta}{g}=\\dfrac{400\\sin60^{\\circ}}{10}=40\\times\\tfrac{\\sqrt3}{2}=20\\sqrt3=34.641$ m.',tags:['projectile','range']},
{id:'PF-CM-23',n:23,lane:'classical',sub:'lagrangian',type:'MCQ',marks:2,diff:'standard',
stem:'A bead slides on a frictionless circular hoop of radius $R$ rotating about its vertical diameter with angular velocity $\\omega=\\sqrt{2g/R}$. The equilibrium angle $\\theta$ (measured from the downward vertical) is',
opts:['$30^{\\circ}$','$45^{\\circ}$','$60^{\\circ}$','$90^{\\circ}$'],
ans:2,
sol:'Effective potential balance gives $\\cos\\theta=\\dfrac{g}{R\\omega^{2}}=\\dfrac{g}{R\\cdot2g/R}=\\dfrac12$, so $\\theta=60^{\\circ}$. (The $\\omega^{2}\\!R\\sin\\theta$ centrifugal term balances $g\\sin\\theta$ projection.)',tags:['rotating-hoop','equilibrium']},
{id:'PF-CM-24',n:24,lane:'classical',sub:'central-orbits',type:'MCQ',marks:2,diff:'standard',
stem:'A particle of mass $m$ moves in the central potential $U(r)=-k/r$ with angular momentum $L$. The radius of the circular orbit is',
opts:['$\\dfrac{L^{2}}{mk}$','$\\dfrac{L^{2}}{2mk}$','$\\dfrac{mk}{L^{2}}$','$\\dfrac{L\\sqrt{k}}{m}$'],
ans:0,
sol:'Circular orbit: $U_{\\mathrm{eff}}=\\dfrac{L^{2}}{2mr^{2}}-\\dfrac{k}{r}$, $\\dfrac{dU_{\\mathrm{eff}}}{dr}=0\\Rightarrow\\dfrac{L^{2}}{mr^{3}}=\\dfrac{k}{r^{2}}$, so $r_{0}=\\dfrac{L^{2}}{mk}$. Check: this equals the Bohr radius structure ✓',tags:['central-force','circular-orbit']},
{id:'PF-CM-25',n:25,lane:'classical',sub:'central-orbits',type:'MSQ',marks:2,diff:'standard',
stem:'For motion in a general central potential $U(r)$, which statements is/are TRUE?',
opts:['The angular momentum $\\mathbf{L}$ is conserved','For conservative $U(r)$ the total energy is conserved','Every bound orbit is a closed curve','For $U(r)\\propto1/r$ the Laplace–Runge–Lenz vector is conserved'],
ans:[0,1,3],
sol:'Central force $\\Rightarrow$ torque-free $\\Rightarrow\\mathbf{L}$ const (A ✓); time-independent conservative force conserves $E$ (B ✓). Bound orbits close only for $U\\propto1/r$ and $U\\propto r^{2}$ (Bertrand) — not in general (C ✗). The LRL vector conservation is the signature $1/r$ symmetry (D ✓).',tags:['central-force','conservation','bertrand']},
{id:'PF-CM-26',n:26,lane:'classical',sub:'small-oscillations',type:'MCQ',marks:2,diff:'standard',
stem:'Two identical masses $m$ are joined to fixed walls and to each other by three identical springs of constant $k$ (wall–mass–mass–wall, all collinear). The ratio $\\omega_{2}/\\omega_{1}$ of the out-of-phase to in-phase normal mode frequencies is',
opts:['$\\sqrt{3}$','$3$','$\\sqrt{2}$','$2$'],
ans:0,
sol:'In-phase: centre spring unstretched, $\\omega_1^2=k/m$. Out-of-phase: centre spring stretch doubles, restoring adds $2kx$ → $\\omega_2^2=3k/m$. Ratio $=\\sqrt{3}$.',tags:['coupled-oscillators','normal-modes']},
{id:'PF-CM-27',n:27,lane:'classical',sub:'hamiltonian',type:'MCQ',marks:1,diff:'seed',
stem:'For the Hamiltonian $H=\\dfrac{p^{2}}{2m}+V(q)$, Hamilton\'s equation for $\\dot{q}$ gives',
opts:['$\\dot{q}=\\dfrac{p}{m}$','$\\dot{q}=-\\dfrac{p}{m}$','$\\dot{q}=\\dfrac{\\partial V}{\\partial q}$','$\\dot{q}=\\dfrac{1}{m}\\dfrac{\\partial V}{\\partial q}$'],
ans:0,
sol:'$\\dot q=\\dfrac{\\partial H}{\\partial p}=\\dfrac{p}{m}$ — canonical momentum equals kinematic momentum here.',tags:['hamilton-equations']},
{id:'PF-CM-28',n:28,lane:'classical',sub:'rigid-body',type:'NAT',marks:2,diff:'standard',
stem:'A solid sphere rolls without slipping down a plane inclined at $30^{\\circ}$. Using $g=10$ m/s$^{2}$, report its acceleration in m/s$^{2}$ (2 d.p.).',
ans:'3.55 to 3.60',
sol:'$a=\\dfrac{g\\sin\\theta}{1+I/(mR^{2})}=\\dfrac{10\\times\\tfrac12}{1+2/5}=\\dfrac{5}{7/5}=\\dfrac{25}{7}=3.571$ m/s$^{2}$.',tags:['rolling','incline']},
{id:'PF-CM-29',n:29,lane:'classical',sub:'canonical',type:'MCQ',marks:2,diff:'apex',
stem:'The transformation $Q=\\ln p$, $P=-qp$ between conjugate pairs $(q,p)\\to(Q,P)$ is canonical. The Poisson bracket $\\{Q,P\\}_{q,p}$ equals',
opts:['$1$','$-1$','$0$','$\\dfrac{q}{p}$'],
ans:0,
sol:'$\\{Q,P\\}_{q,p}=\\partial_qQ\\,\\partial_pP-\\partial_pQ\\,\\partial_qP=(0)(-q)-\\left(\\tfrac1p\\right)(-p)=1$. Unity bracket is exactly the canonicality condition ✓',tags:['poisson-bracket','canonical-transform']},
{id:'PF-CM-30',n:30,lane:'classical',sub:'small-oscillations',type:'MSQ',marks:2,diff:'standard',
stem:'For a holonomic system with $n$ generalized coordinates oscillating about stable equilibrium, which statements is/are TRUE?',
opts:['Each normal coordinate oscillates at a single definite frequency','There are exactly $n$ normal modes (counting degenerate ones with multiplicity)','All normal-mode frequencies are necessarily distinct','Normal-mode eigenvectors can be chosen orthogonal with respect to the mass (kinetic) matrix'],
ans:[0,1,3],
sol:'Normal coordinates diagonalize both quadratic forms: $Q_k\\propto\\cos(\\omega_kt+\\phi_k)$ (A ✓); $n$ modes with multiplicity (B ✓); degeneracies are possible e.g. isotropic systems (C ✗); the secular problem is a generalized eigenvalue equation, so modes are $M$-orthogonal (D ✓).',tags:['normal-modes','diagonalization']},
]
