/* PAPERFORGE S3 · LEGION I · part 1/6 — MATH PHYSICS Q1-10
   Original items, authored+re-derived 2026-08-17 (double-solve journal:
   _audit/paperforge/forge_journal.md). Clean strings only — no audit chatter.
   Schema: {id,n,lane,sub,type,marks,diff,stem,opts,ans,sol,tags}
   MCQ: ans=int index · MSQ: ans=sorted int array · NAT: ans=string */
[
{id:'PF-MP-01',n:1,lane:'mathphys',sub:'linear-algebra',type:'MCQ',marks:1,diff:'seed',
stem:'Let $A=\\begin{pmatrix}2&1\\\\1&2\\end{pmatrix}$. The eigenvalues of $A^{3}$ are',
opts:['$1$ and $3$','$1$ and $9$','$1$ and $27$','$3$ and $27$'],
ans:2,
sol:'$\\det(A-\\lambda I)=(2-\\lambda)^2-1=0\\Rightarrow\\lambda=1,\\,3$. Eigenvalues of $A^3$ are the cubes: $1$ and $27$. Check: $\\det A^3=(\\det A)^3=27=1\\times27$ ✓',tags:['eigenvalues','matrix-power']},
{id:'PF-MP-02',n:2,lane:'mathphys',sub:'linear-algebra',type:'NAT',marks:1,diff:'standard',
stem:'Let $M=\\begin{pmatrix}1&2&3\\\\0&4&5\\\\0&0&6\\end{pmatrix}$ and define $\\lambda=\\dfrac{\\det M}{\\det M^{T}}$. The value of $\\lambda$ is',
ans:'1',
sol:'$M$ is upper triangular: $\\det M=1\\cdot4\\cdot6=24$. Since $\\det M^T=\\det M$ always, $\\lambda=24/24=1$.',tags:['determinant','transpose']},
{id:'PF-MP-03',n:3,lane:'mathphys',sub:'linear-algebra',type:'MSQ',marks:2,diff:'standard',
stem:'Consider $S=\\begin{pmatrix}3&0&0\\\\0&1&2\\\\0&2&1\\end{pmatrix}$. Which of the following statements is/are TRUE?',
opts:['All eigenvalues of $S$ are real','$S$ is positive definite','The eigenvalue $3$ has algebraic multiplicity two','$\\mathrm{Tr}\\,S=5$'],
ans:[0,2,3],
sol:'$S$ is block-diagonal: $[3]\\oplus\\begin{pmatrix}1&2\\\\2&1\\end{pmatrix}$, whose block eigenvalues are $1\\pm2=3,\\,-1$. Spectrum: $\\{3,3,-1\\}$. Real symmetric $\\Rightarrow$ real spectrum (A ✓). $-1<0$ so NOT positive definite (B ✗). $\\lambda=3$ has multiplicity 2 (C ✓). $\\mathrm{Tr}\\,S=3+1+1=5$, also $3+3-1=5$ (D ✓).',tags:['symmetric-matrix','spectrum','trace']},
{id:'PF-MP-04',n:4,lane:'mathphys',sub:'linear-algebra',type:'MCQ',marks:2,diff:'apex',
stem:'A real $3\\times3$ matrix $N$ satisfies $N^{3}=0$ but $N^{2}\\neq0$. The rank of $N^{2}$ is',
opts:['$0$','$1$','$2$','$3$'],
ans:1,
sol:'$N$ is nilpotent; its Jordan form consists of nilpotent blocks. $N^2\\neq0$ needs a block of size $\\ge3$; the matrix is $3\\times3$, so $N\\sim J_3(0)$ exactly. Then $N^2\\sim J_3(0)^2$, which has a single non-zero super-superdiagonal entry: rank $1$. Check: nullity chain $3\\to2\\to1$ forces ranks $2,1,0$ ✓',tags:['nilpotent','jordan','rank']},
{id:'PF-MP-05',n:5,lane:'mathphys',sub:'complex-analysis',type:'MCQ',marks:1,diff:'seed',
stem:'The residue of $f(z)=\\dfrac{\\cos z}{z^{3}}$ at $z=0$ is',
opts:['$1$','$-\\dfrac{1}{2}$','$\\dfrac{1}{2}$','$0$'],
ans:1,
sol:'$\\cos z=1-\\dfrac{z^2}{2!}+\\cdots\\Rightarrow f(z)=\\dfrac{1}{z^3}-\\dfrac{1}{2z}+\\cdots$ The $z^{-1}$ coefficient is $-\\tfrac12$. Check: pole of order 3, $\\operatorname{Res}=\\tfrac{1}{2!}\\lim_{z\\to0}(\\cos z)\'\'=-\\tfrac12$ ✓',tags:['residue','laurent']},
{id:'PF-MP-06',n:6,lane:'mathphys',sub:'complex-analysis',type:'NAT',marks:2,diff:'standard',fig:'mp-contour-poles',
stem:'Evaluate $\\displaystyle\\oint_{C_R}\\frac{dz}{z^{2}+4z+13}$ where $C_R$ is the circle $|z|=4$ traversed counter-clockwise (figure: both poles enclosed — poles marked at $z_{1,2}=-2\\pm3i$). Give the exact numerical value.',
ans:'0',
sol:'Poles at $z=-2\\pm3i$, $|z|=\\sqrt{13}\\approx3.61<4$: both inside $C_R$. Residues: $\\dfrac{1}{z_+-z_-}=\\dfrac{1}{6i}$ and $\\dfrac{1}{z_--z_+}=-\\dfrac{1}{6i}$ — they cancel exactly. The integral is $2\\pi i\\times0=0$.',tags:['contour','residue-cancellation']},
{id:'PF-MP-07',n:7,lane:'mathphys',sub:'complex-analysis',type:'MCQ',marks:2,diff:'standard',
stem:'$\\displaystyle\\int_{0}^{\\infty}\\frac{dx}{x^{4}+1}$ equals',
opts:['$\\dfrac{\\pi}{4}$','$\\dfrac{\\pi}{2\\sqrt2}$','$\\dfrac{\\pi}{\\sqrt2}$','$\\dfrac{\\pi\\sqrt2}{3}$'],
ans:1,
sol:'Even integrand: $\\int_{-\\infty}^{\\infty}=2I$. Upper half-plane poles of $1/(z^4+1)$ are $z_0=e^{i\\pi/4},e^{i3\\pi/4}$, each simple with $\\operatorname{Res}=1/(4z_0^3)=-z_0/4$ (using $z_0^4=-1$). Sum $=-\\tfrac14(e^{i\\pi/4}+e^{i3\\pi/4})=-\\tfrac{i\\sqrt2}{4}$. Then $2I=2\\pi i\\left(-\\tfrac{i\\sqrt2}{4}\\right)=\\tfrac{\\pi\\sqrt2}{2}=\\tfrac{\\pi}{\\sqrt2}$, so $I=\\tfrac{\\pi}{2\\sqrt2}$. Check: $\\int_0^\\infty\\tfrac{dx}{1+x^n}=\\tfrac{\\pi}{n}\\csc\\tfrac{\\pi}{n}$ at $n=4$ gives $\\tfrac{\\pi}{4}\\sqrt2=\\tfrac{\\pi}{2\\sqrt2}$ ✓',tags:['real-integral','residue-method']},
{id:'PF-MP-08',n:8,lane:'mathphys',sub:'ode-pde',type:'MCQ',marks:1,diff:'seed',
stem:'The solution of $y\'\'+4y=0$ with $y(0)=0$, $y\'(0)=8$ is',
opts:['$y=4\\sin 2x$','$y=2\\sin 4x$','$y=4\\sin 4x$','$y=8\\sin 2x$'],
ans:0,
sol:'$y=A\\cos2x+B\\sin2x$; $y(0)=A=0$; $y\'(0)=2B=8\\Rightarrow B=4$. Check: $y\'\'=-16\\sin2x=-4y$ ✓',tags:['ode','initial-value']},
{id:'PF-MP-09',n:9,lane:'mathphys',sub:'fourier',type:'MCQ',marks:2,diff:'standard',
stem:'The $2\\pi$-periodic square wave $f(x)=+1$ for $0<x<\\pi$ and $f(x)=-1$ for $-\\pi<x<0$ has Fourier series $\\sum_{n\\ge1}b_n\\sin nx$. The coefficient $b_3$ is',
opts:['$\\dfrac{4}{3\\pi}$','$\\dfrac{2}{3\\pi}$','$\\dfrac{4}{\\pi}$','$0$'],
ans:0,
sol:'Only sine terms survive (odd function). $b_n=\\dfrac{1}{\\pi}\\int_{-\\pi}^{\\pi}f\\sin nx\\,dx=\\dfrac{2}{\\pi}\\int_0^\\pi\\sin nx\\,dx=\\dfrac{2}{n\\pi}(1-\\cos n\\pi)$, which is $\\dfrac{4}{n\\pi}$ for odd $n$. Hence $b_3=\\dfrac{4}{3\\pi}$. Check: standard series $\\tfrac{4}{\\pi}\\left(\\sin x+\\tfrac{\\sin3x}{3}+\\cdots\\right)$ ✓',tags:['fourier-series','square-wave']},
{id:'PF-MP-10',n:10,lane:'mathphys',sub:'probability',type:'NAT',marks:1,diff:'standard',
stem:'A fair die is rolled twice and $X$ is the larger of the two outcomes. Compute $36\\,E[X]$ and report the integer.',
ans:'161',
sol:'$P(X=k)=P(\\max=k)=\\dfrac{2k-1}{36}$. So $E[X]=\\dfrac{1}{36}\\sum_{k=1}^{6}k(2k-1)=\\dfrac{2\\cdot91-21}{36}=\\dfrac{161}{36}$, giving $36E[X]=161$.',tags:['expectation','order-statistic']},
]
