/* PAPERFORGE S3 · LEGION I · part 5/6 — ELECTROMAGNETIC THEORY Q41-50 */
[
{id:'PF-EM-41',n:41,lane:'emtheory',sub:'electrostatics',type:'MCQ',marks:1,diff:'seed',
stem:'A point charge $q$ sits at the centre of a cube. The electric flux through ONE face of the cube is',
opts:['$\\dfrac{q}{\\varepsilon_{0}}$','$\\dfrac{q}{6\\varepsilon_{0}}$','$\\dfrac{q}{24\\varepsilon_{0}}$','$0$'],
ans:1,
sol:'Gauss: total flux $q/\\varepsilon_0$; by the 6-fold symmetry each face carries $q/(6\\varepsilon_0)$. (Corner placement would give $q/(24\\varepsilon_0)$ — the distractor.)',tags:['gauss-law','flux']},
{id:'PF-EM-42',n:42,lane:'emtheory',sub:'electrostatics',type:'MCQ',marks:1,diff:'seed',
stem:'An infinite line charge of density $\\lambda$ produces, at perpendicular distance $s$, an electric field of magnitude',
opts:['$\\dfrac{\\lambda}{4\\pi\\varepsilon_{0}s}$','$\\dfrac{\\lambda}{2\\pi\\varepsilon_{0}s}$','$\\dfrac{\\lambda}{2\\pi\\varepsilon_{0}s^{2}}$','$\\dfrac{\\lambda}{\\pi\\varepsilon_{0}s}$'],
ans:1,
sol:'Cylindrical Gauss pillbox of length $\\ell$: $E\\,(2\\pi s\\ell)=\\lambda\\ell/\\varepsilon_0\\Rightarrow E=\\dfrac{\\lambda}{2\\pi\\varepsilon_0 s}$.',tags:['gauss-law','line-charge']},
{id:'PF-EM-43',n:43,lane:'emtheory',sub:'electrostatics',type:'NAT',marks:2,diff:'standard',
stem:'A coaxial cable has inner radius $a=1$ mm and outer radius $b=2$ mm. Report its capacitance per unit length in pF/m (1 d.p.).',
ans:'80.0 to 80.5',
sol:'$C^{\\prime}=\\dfrac{2\\pi\\varepsilon_0}{\\ln(b/a)}=\\dfrac{2\\pi\\times8.854\\times10^{-12}}{\\ln2}=\\dfrac{5.563\\times10^{-11}}{0.6931}=8.03\\times10^{-11}$ F/m $=80.3$ pF/m.',tags:['capacitance','coaxial']},
{id:'PF-EM-44',n:44,lane:'emtheory',sub:'electrostatics',type:'MCQ',marks:2,diff:'standard',
stem:'A point charge $q$ is held a distance $d$ above an infinite grounded conducting plane. The magnitude of the force on the charge is',
opts:['$\\dfrac{q^{2}}{16\\pi\\varepsilon_{0}d^{2}}$','$\\dfrac{q^{2}}{4\\pi\\varepsilon_{0}d^{2}}$','$\\dfrac{q^{2}}{8\\pi\\varepsilon_{0}d^{2}}$','$\\dfrac{q^{2}}{32\\pi\\varepsilon_{0}d^{2}}$'],
ans:0,
sol:'Image method: image $-q$ at depth $d$; separation $2d$: $F=\\dfrac{q^{2}}{4\\pi\\varepsilon_0(2d)^{2}}=\\dfrac{q^{2}}{16\\pi\\varepsilon_0 d^{2}}$, attractive.',tags:['image-charges','method-of-images']},
{id:'PF-EM-45',n:45,lane:'emtheory',sub:'magnetostatics',type:'NAT',marks:1,diff:'standard',
stem:'A circular loop of radius $0.1$ m carries $5$ A. Report the magnetic field at its centre in $\\mu$T (1 d.p.).',
ans:'31.3 to 31.5',
sol:'$B=\\dfrac{\\mu_0 I}{2R}=\\dfrac{(4\\pi\\times10^{-7})(5)}{2\\times0.1}=\\pi\\times10^{-5}=3.14\\times10^{-5}\\,\\mathrm{T}=31.4\\,\\mu$T.',tags:['biot-savart','loop-centre']},
{id:'PF-EM-46',n:46,lane:'emtheory',sub:'magnetostatics',type:'MCQ',marks:2,diff:'standard',
stem:'An ideal toroid has $N$ turns carrying current $I$. At a point inside the core at radius $r$ (between inner and outer radii), the field magnitude is',
opts:['$\\mu_{0}NI$','$\\dfrac{\\mu_{0}NI}{2\\pi r}$','$\\dfrac{\\mu_{0}NI}{2r}$','$\\dfrac{\\mu_{0}NI}{4\\pi r}$'],
ans:1,
sol:'Ampère loop of radius $r$ through the core encloses all $N$ turns: $B\\cdot2\\pi r=\\mu_0 NI\\Rightarrow B=\\dfrac{\\mu_0 NI}{2\\pi r}$.',tags:['ampere-law','toroid']},
{id:'PF-EM-47',n:47,lane:'emtheory',sub:'magnetostatics',type:'MSQ',marks:2,diff:'standard',
stem:'In magnetostatics, which statements is/are TRUE?',
opts:['$\\nabla\\cdot\\mathbf{B}=0$','$\\mathbf{B}$-field lines always form closed loops','The magnetic force on a moving charge does no work','$\\nabla\\times\\mathbf{B}=0$ wherever current density is non-zero'],
ans:[0,1,2],
sol:'No magnetic monopoles: $\\nabla\\cdot\\mathbf B=0$ (A ✓); lines are closed (B ✓). $\\mathbf F_m=q\\mathbf v\\times\\mathbf B\\perp\\mathbf v\\Rightarrow$ zero work (C ✓). Ampère: $\\nabla\\times\\mathbf B=\\mu_0\\mathbf J\\neq0$ where $\\mathbf J\\neq0$ (D ✗).',tags:['maxwell-static','magnetic-work']},
{id:'PF-EM-48',n:48,lane:'emtheory',sub:'induction',type:'NAT',marks:2,diff:'standard',
stem:'A conducting rod of length $1$ m slides at $5$ m/s on frictionless rails across a uniform $B=2$ T perpendicular to the rail plane. The loop resistance is $4\\,\\Omega$. Report the dissipated power in watts (integer).',
ans:'25',
sol:'EMF $\\mathcal E=BLv=2\\times1\\times5=10$ V; $P=\\mathcal E^{2}/R=100/4=25$ W. (Equals mechanical power $F_{\\rm mag}v$: $B I L v=B\\,(\\mathcal E/R)\\,L\\,v=2\\cdot2.5\\cdot1\\cdot5=25$ ✓)',tags:['motional-emf','lenz-power']},
{id:'PF-EM-49',n:49,lane:'emtheory',sub:'maxwell',type:'MCQ',marks:1,diff:'standard',
stem:'A parallel-plate capacitor is being charged by a conduction current $I$. The displacement current between the plates equals',
opts:['$\\dfrac{I}{2}$','$I$','$2I$','$0$'],
ans:1,
sol:'$I_d=\\varepsilon_0\\dfrac{d\\Phi_E}{dt}=\\dfrac{dQ_{\\rm enc}}{dt}=I$ — exactly the conduction current, which is what makes $\\nabla\\times\\mathbf B=\\mu_0\\mathbf J+\\mu_0\\varepsilon_0\\partial_t\\mathbf E$ consistent on either spanning surface.',tags:['displacement-current','maxwell']},
{id:'PF-EM-50',n:50,lane:'emtheory',sub:'waves',type:'MCQ',marks:1,diff:'standard',
stem:'A plane electromagnetic wave in vacuum has peak electric field $E_{0}=100$ V/m. Its peak magnetic field $B_{0}$ is about',
opts:['$3.33\\times10^{-7}$ T','$3.33\\times10^{7}$ T','$3.00\\times10^{-7}$ T','$1.00\\times10^{-5}$ T'],
ans:0,
sol:'$B_0=E_0/c=100/(3\\times10^{8})=3.33\\times10^{-7}$ T.',tags:['em-wave','impedance-relation']},
]
