/* PAPERFORGE S3 · LEGION I · part 4/6 — CLASSICAL MECHANICS Q31-40 */
[
{id:'PF-CM-31',n:31,lane:'classical',sub:'rigid-body',type:'MCQ',marks:1,diff:'seed',
stem:'The moment of inertia of a uniform solid sphere of mass $M$ and radius $R$ about a diameter is',
opts:['$\\dfrac{2}{5}MR^{2}$','$\\dfrac{2}{3}MR^{2}$','$\\dfrac{1}{2}MR^{2}$','$\\dfrac{7}{5}MR^{2}$'],
ans:0,
sol:'$I=\\int r_{\\perp}^{2}dm=\\dfrac{2}{5}MR^{2}$ for a solid sphere ($\\tfrac23MR^2$ is the hollow shell; $\\tfrac12MR^2$ a disk/cylinder about its axis; $\\tfrac75MR^2$ the sphere about a tangent — parallel axis check ✓).',tags:['moment-of-inertia']},
{id:'PF-CM-32',n:32,lane:'classical',sub:'relativity',type:'NAT',marks:2,diff:'standard',
stem:'A muon with proper lifetime $\\tau_{0}=2.2\\,\\mu$s travels at $0.99c$. Report its laboratory-frame lifetime in $\\mu$s (1 d.p.).',
ans:'15.4 to 15.7',
sol:'$\\gamma=1/\\sqrt{1-0.99^{2}}=1/\\sqrt{0.0199}=7.089$. Lab lifetime $\\tau=\\gamma\\tau_{0}=7.089\\times2.2=15.60\\,\\mu$s.',tags:['time-dilation','muon']},
{id:'PF-CM-33',n:33,lane:'classical',sub:'rigid-body',type:'MCQ',marks:2,diff:'apex',
stem:'A rigid body with principal moments $I_{1}<I_{2}<I_{3}$ rotates freely (zero torque). Steady rotation is STABLE about',
opts:['the $I_{2}$ axis only','the $I_{1}$ axis only','the $I_{1}$ and $I_{3}$ axes','all three principal axes'],
ans:2,
sol:'Euler equations give $\\ddot\\theta\\propto-\\left[\\tfrac{(I_{3}-I_{1})(I_{2}-I_{1})}{I_{2}I_{3}}\\right]$-type restoring coefficients about $I_1$ and $I_3$; about $I_2$ the coefficient sign flips (intermediate-axis theorem — tennis-racket instability). Stable: $I_1, I_3$.',tags:['euler-equations','stability']},
{id:'PF-CM-34',n:34,lane:'classical',sub:'lagrangian',type:'MCQ',marks:1,diff:'seed',
stem:'The principle of virtual work for a system in static equilibrium with ideal constraints states that the virtual work of',
opts:['all forces, including constraints, vanishes','the applied forces alone vanishes for any virtual displacement consistent with the constraints','the constraint forces is maximal','the applied forces equals the kinetic energy'],
ans:1,
sol:'Ideal (workless) constraints drop out of $\\delta W=\\sum_i\\mathbf{F}^{\\rm appl}_i\\cdot\\delta\\mathbf{r}_i$; equilibrium $\\Leftrightarrow$ virtual work of applied forces vanishes for every constraint-consistent $\\delta\\mathbf r$.',tags:['virtual-work','dAlembert']},
{id:'PF-CM-35',n:35,lane:'classical',sub:'newtonian',type:'NAT',marks:2,diff:'standard',
stem:'A puck on a frictionless horizontal table at the Earth\'s north pole moves horizontally at $10$ m/s. Taking $\\omega_{\\oplus}=7.27\\times10^{-5}$ rad/s, report the magnitude of its Coriolis acceleration in units of $10^{-3}$ m/s$^{2}$ (2 d.p.).',
ans:'1.45 to 1.46',
sol:'At the pole the horizontal velocity is perpendicular to $\\boldsymbol\\omega$: $a_{\\rm Cor}=2\\omega v^{\\prime}=2\\times7.27\\times10^{-5}\\times10=1.454\\times10^{-3}$ m/s$^{2}$, i.e. $1.45$ in units of $10^{-3}$ m/s$^{2}$ (2 d.p.).',tags:['coriolis','rotating-frame']},
{id:'PF-CM-36',n:36,lane:'classical',sub:'fluids',type:'MCQ',marks:1,diff:'seed',
stem:'An open tank has water filled to height $h$ above a small side orifice. The efflux speed (Torricelli) is',
opts:['$\\sqrt{gh}$','$\\sqrt{2gh}$','$2\\sqrt{gh}$','$\\sqrt{\\dfrac{gh}{2}}$'],
ans:1,
sol:'Bernoulli between the free surface and the jet (both at atmospheric pressure, surface speed $\\approx0$): $\\tfrac12 v^{2}=gh\\Rightarrow v=\\sqrt{2gh}$.',tags:['bernoulli','torricelli']},
{id:'PF-CM-37',n:37,lane:'classical',sub:'relativity',type:'MCQ',marks:2,diff:'standard',
stem:'A particle has rest energy $mc^{2}=0.3$ GeV and momentum $pc=0.4$ GeV. Its total energy is',
opts:['$0.4$ GeV','$0.5$ GeV','$0.7$ GeV','$0.12$ GeV'],
ans:1,
sol:'$E=\\sqrt{(pc)^{2}+(mc^{2})^{2}}=\\sqrt{0.16+0.09}=\\sqrt{0.25}=0.5$ GeV. (3-4-5 triangle ✓)',tags:['energy-momentum','relativity']},
{id:'PF-CM-38',n:38,lane:'classical',sub:'central-orbits',type:'MCQ',marks:2,diff:'apex',
stem:'The apsidal angle (angle between successive perihelion and aphelion) for a nearly circular orbit in the 2-D isotropic harmonic-oscillator potential $U(r)=\\tfrac12kr^{2}$ is',
opts:['$\\dfrac{\\pi}{4}$','$\\dfrac{\\pi}{2}$','$\\pi$','$2\\pi$'],
ans:1,
sol:'For a power-law force $F\\propto r^{n}$ the apsidal angle for nearly circular orbits is $\\pi/\\sqrt{3+n}$. Oscillator: $n=1\\Rightarrow\\pi/\\sqrt4=\\pi/2$. (Kepler check: $n=-2\\Rightarrow\\pi$; closed ellipses ✓.)',tags:['apsidal-angle','bertrand']},
{id:'PF-CM-39',n:39,lane:'classical',sub:'newtonian',type:'NAT',marks:2,diff:'standard',
stem:'An Atwood machine carries $m_1=1$ kg and $m_2=2$ kg; the pulley is a uniform disk of mass $M=2$ kg (rope does not slip). Taking $g=9.8$ m/s$^{2}$, report the acceleration in m/s$^{2}$ (2 d.p.).',
ans:'2.43 to 2.47',
sol:'$a=\\dfrac{(m_2-m_1)g}{m_1+m_2+I/R^{2}}=\\dfrac{(1)(9.8)}{1+2+1}=\\dfrac{9.8}{4}=2.45$ m/s$^{2}$ (disk: $I=\\tfrac12MR^{2}$).',tags:['atwood','massive-pulley']},
{id:'PF-CM-40',n:40,lane:'classical',sub:'hamiltonian',type:'MSQ',marks:2,diff:'apex',
stem:'By Noether\'s theorem, which continuous-symmetry → conservation-law pairings are correct?',
opts:['Time-translation $\\to$ energy conservation','Space-translation $\\to$ linear momentum conservation','Rotation $\\to$ angular momentum conservation','Parity $\\to$ action conservation'],
ans:[0,1,2],
sol:'A, B, C are the three canonical spacetime examples of Noether\'s theorem. Parity is a DISCRETE symmetry — Noether\'s theorem (first) does not yield a conserved current for it, and "action conservation" is not a law (D ✗).',tags:['noether','symmetries']},
]
