/* PAPERFORGE S5 · LEGION CS-I · part 3/7 — PART B (core, +3.5 / −0.875) Q21-33
   Original items, authored+re-derived 2026-08-18. Schema as in pfcs_p1.js. */
[
{id:'PF-CS-B01',n:21,part:'B',lane:'mathphys',sub:'vector-calculus',type:'MCQ',marks:3.5,diff:'seed',
stem:'For any twice-differentiable scalar field $\\phi(\\mathbf{r})$, the field $\\nabla\\times(\\nabla\\phi)$ is',
opts:['identically zero','$\\nabla^2\\phi$','equal to $-\\nabla\\phi$','divergence-free only in two dimensions'],
ans:0,
sol:'Curl of a gradient vanishes identically: components are differences of mixed partials, which cancel by symmetry of second derivatives. It holds in any dimension.',tags:['curl-gradient']},
{id:'PF-CS-B02',n:22,part:'B',lane:'mathphys',sub:'linear-algebra',type:'MCQ',marks:3.5,diff:'standard',
stem:'The eigenvalues of the rotation matrix $\\begin{pmatrix}\\cos\\theta&-\\sin\\theta\\\\ \\sin\\theta&\\phantom{-}\\cos\\theta\\end{pmatrix}$ are',
opts:['$\\pm1$','$e^{\\pm i\\theta}$','$\\pm\\cos\\theta$','$\\pm i\\sin\\theta$'],
ans:1,
sol:'$\\lambda^2-2\\lambda\\cos\\theta+1=0$ gives $\\lambda=\\cos\\theta\\pm i\\sin\\theta=e^{\\pm i\\theta}$, both of unit modulus as any rotation demands.',tags:['eigenvalues','rotation']},
{id:'PF-CS-B03',n:23,part:'B',lane:'mathphys',sub:'fourier-series',type:'MCQ',marks:3.5,diff:'apex',
stem:'The Fourier series of $f(x)=x^2$ on $(-\\pi,\\pi)$, evaluated at the endpoint $x=\\pi$, converges to',
opts:['$0$','$\\pi^2/2$','$\\pi^2$','$2\\pi^2$'],
ans:2,
sol:'Dirichlet: the series converges to $\\tfrac12[f(\\pi^-)+f(-\\pi^+)]=\\tfrac12(\\pi^2+\\pi^2)=\\pi^2$, since the periodic extension is continuous there.',tags:['dirichlet-theorem']},
{id:'PF-CS-B04',n:24,part:'B',lane:'classical',sub:'torque',type:'MCQ',marks:3.5,diff:'standard',
stem:'A force $\\mathbf{F}=5\\hat{k}\\,\\mathrm{N}$ acts at the point $\\mathbf{r}=(4\\hat{i}+3\\hat{j})\\,\\mathrm{m}$. The magnitude of the torque about the origin is',
opts:['$15\\,\\mathrm{N\\,m}$','$20\\,\\mathrm{N\\,m}$','$25\\,\\mathrm{N\\,m}$','$35\\,\\mathrm{N\\,m}$'],
ans:2,
sol:'$\\boldsymbol\\tau=\\mathbf r\\times\\mathbf F=15\\hat i-20\\hat j\\,\\mathrm{N\\,m}$, so $|\\boldsymbol\\tau|=\\sqrt{15^2+20^2}=25\\,\\mathrm{N\\,m}$.',tags:['cross-product']},
{id:'PF-CS-B05',n:25,part:'B',lane:'classical',sub:'gravitation',type:'MCQ',marks:3.5,diff:'standard',
stem:'For a body moving in a bound Kepler orbit (ellipse), its total mechanical energy is',
opts:['positive','zero','negative','sign-changing over one orbit'],
ans:2,
sol:'Bound orbits have $E<0$: the semi-major axis is $a=-GMm/(2E)$, which is positive only for negative $E$; $E=0$ is the parabolic escape threshold.',tags:['orbits','energy']},
{id:'PF-CS-B06',n:26,part:'B',lane:'classical',sub:'atwood',type:'MCQ',marks:3.5,diff:'standard',
stem:'An ideal Atwood machine carries masses $2m$ and $m$. The acceleration of the masses is',
opts:['$g/6$','$g/3$','$g/2$','$2g/3$'],
ans:1,
sol:'$a=(m_1-m_2)g/(m_1+m_2)=(2m-m)g/(3m)=g/3$. The string tension is $4mg/3$.',tags:['constraint-motion']},
{id:'PF-CS-B07',n:27,part:'B',lane:'emtheory',sub:'electrostatics',type:'MCQ',marks:3.5,diff:'seed',
stem:'The electric field of an infinite line charge of uniform density $\\lambda$, at perpendicular distance $r$ from the line, falls off as',
opts:['$1/r^2$','$1/r$','$r^0$ (independent of $r$)','$e^{-r}$'],
ans:1,
sol:'Gauss law on a coaxial cylinder: $E\\cdot2\\pi rL=\\lambda L/\\varepsilon_0$, so $E=\\lambda/(2\\pi\\varepsilon_0 r)\\propto1/r$.',tags:['gauss-law']},
{id:'PF-CS-B08',n:28,part:'B',lane:'emtheory',sub:'capacitance',type:'MCQ',marks:3.5,diff:'standard',fig:'em-gauss-pillbox',
stem:'In the parallel-plate arrangement of the figure ($E=\\sigma/\\varepsilon_0$ between the plates), the plate separation is halved while area and charge are kept fixed. The capacitance',
opts:['is halved','is doubled','stays unchanged','quadruples'],
ans:1,
sol:'$C=\\varepsilon_0 A/d$: halving $d$ doubles $C$. (The field $E=\\sigma/\\varepsilon_0$ is set by the charge density and is itself unchanged.)',tags:['parallel-plate']},
{id:'PF-CS-B09',n:29,part:'B',lane:'emtheory',sub:'magnetostatics',type:'MCQ',marks:3.5,diff:'standard',
stem:'A long ideal solenoid with $n=500$ turns per metre carries $I=2\\,\\mathrm{A}$. The magnetic field inside it is',
opts:['$0.13\\,\\mathrm{mT}$','$1.26\\,\\mathrm{mT}$','$12.6\\,\\mathrm{mT}$','$126\\,\\mathrm{mT}$'],
ans:1,
sol:'$B=\\mu_0nI=4\\pi\\times10^{-7}\\times500\\times2=4\\pi\\times10^{-4}=1.26\\times10^{-3}\\,\\mathrm{T}=1.26\\,\\mathrm{mT}$.',tags:['solenoid']},
{id:'PF-CS-B10',n:30,part:'B',lane:'emtheory',sub:'em-waves',type:'MCQ',marks:3.5,diff:'seed',
stem:'For a plane electromagnetic wave in vacuum, the ratio of the electric to magnetic field amplitudes $E_0/B_0$ equals',
opts:['$1/c$','$c$','$c^2$','$\\sqrt{\\mu_0/\\varepsilon_0}/c$ only'],
ans:1,
sol:'Faraday induction on a plane wave gives $E_0=cB_0$, hence $E_0/B_0=c=3\\times10^{8}\\,\\mathrm{m/s}$.',tags:['plane-wave']},
{id:'PF-CS-B11',n:31,part:'B',lane:'quantum',sub:'photons',type:'MCQ',marks:3.5,diff:'standard',
stem:'The energy of a photon of wavelength $500\\,\\mathrm{nm}$ is approximately',
opts:['$1.24\\,\\mathrm{eV}$','$2.48\\,\\mathrm{eV}$','$4.96\\,\\mathrm{eV}$','$6.20\\,\\mathrm{eV}$'],
ans:1,
sol:'$E=hc/\\lambda=1240\\,\\mathrm{eV\\,nm}/500\\,\\mathrm{nm}=2.48\\,\\mathrm{eV}$.',tags:['photon-energy']},
{id:'PF-CS-B12',n:32,part:'B',lane:'quantum',sub:'square-well',type:'MCQ',marks:3.5,diff:'standard',
stem:'If the width of a one-dimensional infinite potential well is doubled, its ground-state energy becomes',
opts:['one half','one quarter','twice','four times'],
ans:1,
sol:'$E_1=\\pi^2\\hbar^2/(2mL^2)\\propto1/L^2$; doubling $L$ divides $E_1$ by $4$.',tags:['scaling']},
{id:'PF-CS-B13',n:33,part:'B',lane:'quantum',sub:'formalism',type:'MCQ',marks:3.5,diff:'seed',
stem:'For a quantum state $\\psi(\\mathbf{r},t)$, the quantity $|\\psi(\\mathbf{r},t)|^2$ represents',
opts:['the probability density for finding the particle near $\\mathbf r$ at time $t$','the total energy density of the particle','the classical trajectory smoothed over one period','the expectation value of the position operator'],
ans:0,
sol:'Born rule: $|\\psi|^2d^3r$ is the probability of locating the particle in $d^3r$; normalisation $\\int|\\psi|^2d^3r=1$ makes it a density, not a probability itself.',tags:['born-rule']}
]
