/* PAPERFORGE S5 · LEGION CS-I · part 5/7 — PART C (advanced, +5 / −1.25) Q46-55
   Original items, authored+re-derived 2026-08-18. Schema as in pfcs_p1.js. */
[
{id:'PF-CS-C01',n:46,part:'C',lane:'mathphys',sub:'complex-analysis',type:'MCQ',marks:5,diff:'standard',
stem:'The value of the contour integral $\\displaystyle\\oint_{|z-i|=1}\\frac{dz}{z^2+1}$ is',
opts:['$\\pi$','$2\\pi$','$\\pi/2$','$0$'],
ans:0,
sol:'Only the pole $z=i$ lies inside the circle $|z-i|=1$; $\\operatorname{Res}_{z=i}\\frac{1}{(z-i)(z+i)}=\\frac{1}{2i}$, so the integral is $2\\pi i\\times\\frac{1}{2i}=\\pi$.',tags:['residue-theorem']},
{id:'PF-CS-C02',n:47,part:'C',lane:'mathphys',sub:'fourier-transform',type:'MCQ',marks:5,diff:'standard',
stem:'The Fourier transform $\\tilde f(k)=\\int_{-\\infty}^{\\infty}e^{-ikx}f(x)\\,dx$ of $f(x)=e^{-2|x|}$, evaluated at $k=0$, is',
opts:['$1/2$','$1$','$2$','$4$'],
ans:1,
sol:'$\\tilde f(0)=\\int_{-\\infty}^{\\infty}e^{-2|x|}dx=2\\int_0^\\infty e^{-2x}dx=2\\times\\tfrac12=1$ (equivalently $2a/(a^2+k^2)$ at $a=2,k=0$).',tags:['fourier-transform']},
{id:'PF-CS-C03',n:48,part:'C',lane:'mathphys',sub:'linear-algebra',type:'MCQ',marks:5,diff:'apex',
stem:'For the nilpotent matrix $A=\\begin{pmatrix}0&1\\\\0&0\\end{pmatrix}$, the exponential $e^{A}$ equals',
opts:['$\\begin{pmatrix}1&1\\\\0&1\\end{pmatrix}$','$\\begin{pmatrix}e&1\\\\0&e\\end{pmatrix}$','$\\begin{pmatrix}1&0\\\\1&1\\end{pmatrix}$','$\\begin{pmatrix}e&0\\\\0&e\\end{pmatrix}$'],
ans:0,
sol:'$A^2=0$ kills every term past linear order: $e^A=I+A=\\begin{pmatrix}1&1\\\\0&1\\end{pmatrix}$.',tags:['matrix-exponential','nilpotent']},
{id:'PF-CS-C04',n:49,part:'C',lane:'mathphys',sub:'vector-calculus',type:'MCQ',marks:5,diff:'standard',
stem:'The circulation $\\oint\\mathbf{F}\\cdot d\\mathbf{l}$ of $\\mathbf{F}=(-y,\\,x,\\,0)$ around the unit circle $x^2+y^2=1$ (counter-clockwise, $z=0$ plane) is',
opts:['$\\pi$','$2\\pi$','$4\\pi$','$0$'],
ans:1,
sol:'$(\\nabla\\times\\mathbf F)_z=\\partial_x(x)-\\partial_y(-y)=2$; Stokes gives $2\\times\\text{area}=2\\pi$. Direct: $x=\\cos t,y=\\sin t$ yields $\\int_0^{2\\pi}(x^2+y^2)dt=2\\pi$.',tags:['stokes-theorem']},
{id:'PF-CS-C05',n:50,part:'C',lane:'classical',sub:'rockets',type:'MCQ',marks:5,diff:'standard',
stem:'A rocket ejects exhaust at $u=2\\,\\mathrm{km/s}$ (relative to the rocket). Ignoring gravity and drag, the speed gained when the mass ratio is $m_0/m=3$ is',
opts:['$1.6\\,\\mathrm{km/s}$','$2.2\\,\\mathrm{km/s}$','$3.0\\,\\mathrm{km/s}$','$6.0\\,\\mathrm{km/s}$'],
ans:1,
sol:'Tsiolkovsky: $\\Delta v=u\\ln(m_0/m)=2\\ln3=2\\times1.0986=2.20\\,\\mathrm{km/s}$.',tags:['variable-mass']},
{id:'PF-CS-C06',n:51,part:'C',lane:'classical',sub:'central-forces',type:'MCQ',marks:5,diff:'apex',
stem:'A particle moves in the isotropic three-dimensional harmonic potential $V(r)=\\tfrac12 kr^2$. The shape of a generic bound orbit is',
opts:['an ellipse with the force centre at one focus','an ellipse centred on the force centre','a precessing rosette that never closes','a parabola with vertex at the force centre'],
ans:1,
sol:'For the isotropic oscillator the solution is $\\mathbf r(t)=\\mathbf A\\cos\\omega t+\\mathbf B\\sin\\omega t$: an ellipse geometrically centred on the centre of force. (Kepler’s law $1/r$ instead puts the centre at a focus.)',tags:['bertrand','orbits']},
{id:'PF-CS-C07',n:52,part:'C',lane:'classical',sub:'projectile',type:'MCQ',marks:5,diff:'seed',
stem:'A projectile is launched at $v=20\\,\\mathrm{m/s}$ at $45^\\circ$ to the horizontal. Taking $g=10\\,\\mathrm{m/s^2}$, its range on level ground is',
opts:['$20\\,\\mathrm{m}$','$40\\,\\mathrm{m}$','$60\\,\\mathrm{m}$','$80\\,\\mathrm{m}$'],
ans:1,
sol:'$R=v^2\\sin(2\\theta)/g=400\\times1/10=40\\,\\mathrm{m}$ — $45^\\circ$ maximises $\\sin 2\\theta$.',tags:['kinematics']},
{id:'PF-CS-C08',n:53,part:'C',lane:'classical',sub:'oscillations',type:'MCQ',marks:5,diff:'apex',
stem:'A damped oscillator follows $x(t)=A_0e^{-t/2\\tau}\\cos\\omega t$. After $t=10\\,\\mathrm{s}$ with $\\tau=2\\,\\mathrm{s}$, the fraction of its initial energy remaining is',
opts:['$e^{-2.5}$','$e^{-5}$','$e^{-10}$','$e^{-20}$'],
ans:1,
sol:'Energy is quadratic in amplitude: $E/E_0=e^{-t/\\tau}=e^{-10/2}=e^{-5}\\approx6.7\\times10^{-3}$. The amplitude halves the exponent rate of the energy.',tags:['damping','energy-decay']},
{id:'PF-CS-C09',n:54,part:'C',lane:'emtheory',sub:'electrostatics',type:'MCQ',marks:5,diff:'standard',
stem:'A thin spherical shell of radius $R$ carries total charge $Q$. The electrostatic potential at any point inside the shell (taking $V(\\infty)=0$) is',
opts:['zero','$kQ/R$, the same everywhere inside','$kQ/r$, varying with interior radius $r$','$kQ/R^2$'],
ans:1,
sol:'Inside, $E=0$, so $V$ is constant; matching at the surface fixes the constant at $kQ/R$. Zero would follow only by wrongly setting $V=0$ wherever $E=0$.',tags:['shell-theorem']},
{id:'PF-CS-C10',n:55,part:'C',lane:'emtheory',sub:'capacitance',type:'MCQ',marks:5,diff:'standard',
stem:'A $2\\,\\mu\\mathrm{F}$ capacitor charged to $100\\,\\mathrm{V}$ is disconnected from the source and connected in parallel (like plates together) with an uncharged $3\\,\\mu\\mathrm{F}$ capacitor. The common voltage across the pair is',
opts:['$60\\,\\mathrm{V}$','$50\\,\\mathrm{V}$','$40\\,\\mathrm{V}$','$20\\,\\mathrm{V}$'],
ans:2,
sol:'Charge is conserved: $Q=2\\,\\mu\\mathrm{F}\\times100\\,\\mathrm{V}=200\\,\\mu\\mathrm{C}$ over $C_{tot}=5\\,\\mu\\mathrm{F}$ gives $V=200/5=40\\,\\mathrm{V}$. (Energy is not conserved — some is lost in redistribution.)',tags:['charge-sharing']}
]
