/* PAPERFORGE S5 · LEGION CS-I · part 6/7 — PART C (advanced, +5 / −1.25) Q56-65
   Original items, authored+re-derived 2026-08-18. Schema as in pfcs_p1.js. */
[
{id:'PF-CS-C11',n:56,part:'C',lane:'emtheory',sub:'method-of-images',type:'MCQ',marks:5,diff:'apex',
stem:'A point charge $q$ sits a distance $d$ above an infinite grounded conducting plane. The magnitude of the force attracting it to the plane is',
opts:['$q^2/(4\\pi\\varepsilon_0 d^2)$','$q^2/(8\\pi\\varepsilon_0 d^2)$','$q^2/(16\\pi\\varepsilon_0 d^2)$','$q^2/(32\\pi\\varepsilon_0 d^2)$'],
ans:2,
sol:'Image charge $-q$ at distance $2d$: $F=q^2/[4\\pi\\varepsilon_0(2d)^2]=q^2/(16\\pi\\varepsilon_0 d^2)$. The halves in plane distance and Coulomb law together give the factor $16$.',tags:['image-charges']},
{id:'PF-CS-C12',n:57,part:'C',lane:'emtheory',sub:'optics',type:'MCQ',marks:5,diff:'standard',fig:'op-thin-lens',
stem:'For the thin-lens arrangement of the figure ($f=15\\,\\mathrm{cm}$, object at $u=30\\,\\mathrm{cm}$), the image distance $v$ and magnification $m$ are',
opts:['$v=30\\,\\mathrm{cm},\\ m=-1$','$v=10\\,\\mathrm{cm},\\ m=-1/2$','$v=30\\,\\mathrm{cm},\\ m=+1$','$v=15\\,\\mathrm{cm},\\ m=-2$'],
ans:0,
sol:'$1/v=1/f-1/u=1/15-1/30=1/30$, so $v=30\\,\\mathrm{cm}$ and $m=-v/u=-1$: a real, inverted, same-size image, exactly what the ray diagram shows.',tags:['thin-lens']},
{id:'PF-CS-C13',n:58,part:'C',lane:'quantum',sub:'tunneling',type:'MCQ',marks:5,diff:'apex',
stem:'Outside a finite-width barrier the wavefunction decays as $\\psi\\sim e^{-\\kappa x}$. The ratio of the probability densities $|\\psi(a+1/\\kappa)|^2/|\\psi(a)|^2$ at two points one penetration depth apart is',
opts:['$e^{-1/2}$','$e^{-1}$','$e^{-2}$','$1/2$'],
ans:2,
sol:'$|\\psi|^2\\sim e^{-2\\kappa x}$, so the ratio over $\\Delta x=1/\\kappa$ is $e^{-2\\kappa/\\kappa}=e^{-2}\\approx0.135$. Probability decays twice as fast as amplitude.',tags:['evanescent-wave']},
{id:'PF-CS-C14',n:59,part:'C',lane:'quantum',sub:'hydrogen',type:'MCQ',marks:5,diff:'standard',
stem:'For the hydrogen $1s$ state, the most probable value of the radial distance $r$ (peak of the radial probability distribution) is',
opts:['$a_0/2$','$a_0$','$\\tfrac{3}{2}a_0$','$2a_0$'],
ans:1,
sol:'The radial density $P(r)=4r^2e^{-2r/a_0}/a_0^3$ peaks where $dP/dr=0$: $2r-2r^2/a_0=0$, i.e. $r=a_0$. Note $\\langle r\\rangle=\\tfrac32a_0$ is the mean, not the peak.',tags:['radial-distribution']},
{id:'PF-CS-C15',n:60,part:'C',lane:'quantum',sub:'perturbation',type:'MCQ',marks:5,diff:'apex',
stem:'A harmonic oscillator of mass $m$ and frequency $\\omega$ is perturbed by $H^{\\prime}=bx^2$. The first-order shift of its ground-state energy is',
opts:['$b\\hbar/(4m\\omega)$','$b\\hbar/(2m\\omega)$','$b\\hbar/(m\\omega)$','$2b\\hbar/(m\\omega)$'],
ans:1,
sol:'$\\Delta E^{(1)}=\\langle0|bx^2|0\\rangle=b\\,\\frac{\\hbar}{2m\\omega}(2n+1)\\big|_{n=0}=b\\hbar/(2m\\omega)$, using $\\langle x^2\\rangle_0=\\hbar/(2m\\omega)$.',tags:['first-order-correction']},
{id:'PF-CS-C16',n:61,part:'C',lane:'quantum',sub:'uncertainty',type:'MCQ',marks:5,diff:'standard',
stem:'For the harmonic-oscillator eigenstate $n=3$, the product $\\Delta x\\,\\Delta p$ equals',
opts:['$3\\hbar$','$\\tfrac72\\hbar$','$\\tfrac52\\hbar$','$4\\hbar$'],
ans:1,
sol:'Every oscillator eigenstate gives $\\Delta x\\Delta p=(n+\\tfrac12)\\hbar$; for $n=3$ this is $\\tfrac72\\hbar$. Only $n=0$ saturates the $\\hbar/2$ bound.',tags:['heisenberg']},
{id:'PF-CS-C17',n:62,part:'C',lane:'thermo',sub:'otto-cycle',type:'MCQ',marks:5,diff:'standard',
stem:'An ideal Otto cycle with compression ratio $r=8$ uses a gas with $\\gamma=1.4$. Its efficiency is closest to',
opts:['$50\\%$','$56.5\\%$','$62\\%$','$71\\%$'],
ans:1,
sol:'$\\eta=1-r^{1-\\gamma}=1-8^{-0.4}=1-1/2.297=1-0.4353=0.565$, i.e. about $56.5\\%$.',tags:['heat-engine']},
{id:'PF-CS-C18',n:63,part:'C',lane:'thermo',sub:'radiation',type:'MCQ',marks:5,diff:'standard',
stem:'The entropy of blackbody radiation in a cavity of volume $V=10^{-3}\\,\\mathrm{m^3}$ at $T=1000\\,\\mathrm{K}$ is (with $a=7.566\\times10^{-16}\\,\\mathrm{J\\,m^{-3}\\,K^{-4}}$) approximately',
opts:['$1.0\\times10^{-9}\\,\\mathrm{J\\,K^{-1}}$','$3.0\\times10^{-10}\\,\\mathrm{J\\,K^{-1}}$','$4.0\\times10^{-9}\\,\\mathrm{J\\,K^{-1}}$','$1.0\\times10^{-12}\\,\\mathrm{J\\,K^{-1}}$'],
ans:0,
sol:'$S=\\tfrac43 aT^3V=\\tfrac43\\times7.566\\times10^{-16}\\times10^{9}\\times10^{-3}=\\tfrac43\\times7.566\\times10^{-10}=1.01\\times10^{-9}\\,\\mathrm{J\\,K^{-1}}$.',tags:['photon-gas']},
{id:'PF-CS-C19',n:64,part:'C',lane:'thermo',sub:'ideal-gas',type:'MCQ',marks:5,diff:'standard',
stem:'One mole of a diatomic ideal gas (rigid rotator) is heated at constant volume from $300\\,\\mathrm{K}$ to $600\\,\\mathrm{K}$. The change in its internal energy is closest to',
opts:['$3.7\\,\\mathrm{kJ}$','$6.2\\,\\mathrm{kJ}$','$8.7\\,\\mathrm{kJ}$','$12.5\\,\\mathrm{kJ}$'],
ans:1,
sol:'$\\Delta U=nC_V\\Delta T=1\\times\\tfrac52R\\times300=2.5\\times8.314\\times300=6235\\,\\mathrm{J}=6.2\\,\\mathrm{kJ}$; constant volume means all heat goes into $U$ with $C_V=5R/2$.',tags:['equipartition']},
{id:'PF-CS-C20',n:65,part:'C',lane:'thermo',sub:'mixing',type:'MCQ',marks:5,diff:'apex',
stem:'One mole of He and one mole of Ar, initially in equal volumes at the same $T$ and $P$, are allowed to mix isothermally. The entropy of mixing is',
opts:['$5.76\\,\\mathrm{J\\,K^{-1}}$','$11.53\\,\\mathrm{J\\,K^{-1}}$','$23.05\\,\\mathrm{J\\,K^{-1}}$','$0$ because the gases stay at the same temperature'],
ans:1,
sol:'Each gas doubles its accessible volume independently: $\\Delta S=R\\ln2+R\\ln2=2R\\ln2=11.53\\,\\mathrm{J\\,K^{-1}}$. Distinct gases mix irreversibly; identical gases would give zero (Gibbs).',tags:['entropy-of-mixing']}
]
