/* PAPERFORGE S5 · LEGION CS-I · part 4/7 — PART B (core, +3.5 / −0.875) Q34-45
   Original items, authored+re-derived 2026-08-18. Schema as in pfcs_p1.js. */
[
{id:'PF-CS-B14',n:34,part:'B',lane:'quantum',sub:'harmonic-oscillator',type:'MCQ',marks:3.5,diff:'standard',
stem:'For the harmonic-oscillator raising operator, $\\hat{a}^\\dagger|2\\rangle$ equals',
opts:['$\\sqrt{2}\\,|1\\rangle$','$\\sqrt{3}\\,|3\\rangle$','$2\\,|3\\rangle$','$\\sqrt{3}\\,|1\\rangle$'],
ans:1,
sol:'$\\hat a^\\dagger|n\\rangle=\\sqrt{n+1}\\,|n+1\\rangle$, so $n=2$ gives $\\sqrt{3}\\,|3\\rangle$.',tags:['ladder-operators']},
{id:'PF-CS-B15',n:35,part:'B',lane:'thermo',sub:'phase-equilibria',type:'MCQ',marks:3.5,diff:'seed',
stem:'The triple-point temperature of water is',
opts:['$273.15\\,\\mathrm{K}$','$273.16\\,\\mathrm{K}$','$373.15\\,\\mathrm{K}$','$0.00\\,\\mathrm{K}$'],
ans:1,
sol:'By definition (and former SI fixing) the water triple point is $273.16\\,\\mathrm{K}=0.01^\\circ$C — note it sits $0.01$ K above the ice point $273.15\\,\\mathrm{K}$.',tags:['triple-point']},
{id:'PF-CS-B16',n:36,part:'B',lane:'thermo',sub:'carnot',type:'MCQ',marks:3.5,diff:'seed',
stem:'A Carnot engine operates between reservoirs at $600\\,\\mathrm{K}$ and $300\\,\\mathrm{K}$. Its efficiency is',
opts:['$25\\%$','$33\\%$','$50\\%$','$67\\%$'],
ans:2,
sol:'$\\eta=1-T_c/T_h=1-300/600=0.5=50\\%$.',tags:['efficiency']},
{id:'PF-CS-B17',n:37,part:'B',lane:'thermo',sub:'entropy',type:'MCQ',marks:3.5,diff:'standard',
stem:'One kilogram of ice melts reversibly at $273\\,\\mathrm{K}$, absorbing a latent heat $L=334\\,\\mathrm{kJ}$. The entropy change of the ice-water system is',
opts:['$0.82\\,\\mathrm{kJ\\,K^{-1}}$','$1.22\\,\\mathrm{kJ\\,K^{-1}}$','$334\\,\\mathrm{kJ\\,K^{-1}}$','$0$'],
ans:1,
sol:'Reversible isothermal phase change: $\\Delta S=L/T=334/273=1.22\\,\\mathrm{kJ\\,K^{-1}}$. It is not zero — entropy is not conserved, only energy is.',tags:['latent-heat']},
{id:'PF-CS-B18',n:38,part:'B',lane:'electronics',sub:'amplifiers',type:'MCQ',marks:3.5,diff:'standard',
stem:'A single-stage common-emitter transistor amplifier introduces, between base input and collector output, a voltage phase shift of',
opts:['$0^\\circ$','$90^\\circ$','$180^\\circ$','$270^\\circ$'],
ans:2,
sol:'Rising base voltage raises collector current and drops the collector node: output and input are inverted, i.e. $180^\\circ$ out of phase (mid-band).',tags:['common-emitter']},
{id:'PF-CS-B19',n:39,part:'B',lane:'electronics',sub:'sources',type:'MCQ',marks:3.5,diff:'seed',
stem:'An ideal voltage source has internal resistance',
opts:['zero','equal to the load resistance','$1\\,\\Omega$','infinite'],
ans:0,
sol:'The terminal voltage of an ideal voltage source never sags with load, which forces internal resistance $R_{int}=0$. (An ideal current source instead has infinite internal resistance.)',tags:['thevenin']},
{id:'PF-CS-B20',n:40,part:'B',lane:'electronics',sub:'digital',type:'MCQ',marks:3.5,diff:'standard',
stem:'A 4-bit binary ripple counter passes through how many distinct states before repeating?',
opts:['$4$','$8$','$16$','$32$'],
ans:2,
sol:'$2^4=16$ states, $0000$ through $1111$, then it wraps.',tags:['counters']},
{id:'PF-CS-B21',n:41,part:'B',lane:'atnuc',sub:'nuclear-structure',type:'MCQ',marks:3.5,diff:'seed',
stem:'Two nuclei are isotopes of each other when they have the same',
opts:['mass number $A$','atomic number $Z$ with different mass numbers','neutron number $N$ with different atomic numbers','binding energy per nucleon'],
ans:1,
sol:'Isotopes share $Z$ (same element, same chemistry) while $N$ and hence $A$ differ, e.g. $^{12}$C and $^{14}$C. Equal $N$ defines isotones; equal $A$ defines isobars.',tags:['isotopes']},
{id:'PF-CS-B22',n:42,part:'B',lane:'atnuc',sub:'nuclear-size',type:'MCQ',marks:3.5,diff:'standard',
stem:'With the nuclear radius law $R=R_0A^{1/3}$, the radius ratio $R(^{27}\\mathrm{Al})/R(^{8}\\mathrm{Be})$ is',
opts:['$1.5$','$2.25$','$3.0$','$3.375$'],
ans:0,
sol:'$R\\propto A^{1/3}$, so the ratio is $(27/8)^{1/3}=3/2=1.5$.',tags:['radius-law']},
{id:'PF-CS-B23',n:43,part:'B',lane:'solidstate',sub:'crystal-structure',type:'MCQ',marks:3.5,diff:'standard',
stem:'The number of atoms per conventional (cubic) unit cell of the diamond structure is',
opts:['$2$','$4$','$8$','$16$'],
ans:2,
sol:'Diamond = FCC lattice ($4$ lattice points) with a two-atom basis, giving $4\\times2=8$ atoms per conventional cell.',tags:['diamond']},
{id:'PF-CS-B24',n:44,part:'B',lane:'solidstate',sub:'semiconductors',type:'MCQ',marks:3.5,diff:'seed',
stem:'The band gap of silicon at room temperature is approximately',
opts:['$0.03\\,\\mathrm{eV}$','$0.67\\,\\mathrm{eV}$','$1.1\\,\\mathrm{eV}$','$5.5\\,\\mathrm{eV}$'],
ans:2,
sol:'$E_g(\\mathrm{Si})\\approx1.1\\,\\mathrm{eV}$ at $300\\,\\mathrm{K}$; $0.67\\,\\mathrm{eV}$ is germanium and $5.5\\,\\mathrm{eV}$ diamond’s insulator-scale gap.',tags:['band-gap']},
{id:'PF-CS-B25',n:45,part:'B',lane:'solidstate',sub:'band-theory',type:'MCQ',marks:3.5,diff:'standard',
stem:'Bloch theorem states that the one-electron wavefunction in a perfect crystal can be written as',
opts:['$\\psi(\\mathbf r)=e^{i\\mathbf k\\cdot\\mathbf r}u_{\\mathbf k}(\\mathbf r)$ with $u_{\\mathbf k}$ having the lattice periodicity','$\\psi(\\mathbf r)=A\\sin(\\mathbf k\\cdot\\mathbf r)$ with uniform amplitude','a plane wave truncated at the first Brillouin zone boundary','a localised Wannier function centred on every site simultaneously'],
ans:0,
sol:'Bloch states are lattice-periodic envelopes $u_{\\mathbf k}(\\mathbf r+\\mathbf R)=u_{\\mathbf k}(\\mathbf r)$ modulating a plane wave $e^{i\\mathbf k\\cdot\\mathbf r}$, the crystalline analogue of Floquet theory.',tags:['bloch-theorem']}
]
