/* PAPERFORGE S5 · LEGION CS-I · part 1/7 — PART A (aptitude) Q1-10 · +2 / −0.5
   Original items, authored+re-derived 2026-08-18 (double-solve journal:
   _audit/paperforge/forge_journal_cs1.md). Clean strings only.
   Schema: {id,n,part,lane,sub,type:'MCQ',marks,diff,stem,opts,ans,sol,tags} */
[
{id:'PF-CS-A01',n:1,part:'A',lane:'aptitude',sub:'number-series',type:'MCQ',marks:2,diff:'seed',
stem:'Find the next term of the series: $2,\\,6,\\,12,\\,20,\\,30,\\,?$',
opts:['$36$','$40$','$42$','$44$'],
ans:2,
sol:'Differences are $4,6,8,10$ — increasing by $2$. Next difference $12$, giving $30+12=42$ (equivalently the terms are $n^2+n$).',tags:['series']},
{id:'PF-CS-A02',n:2,part:'A',lane:'aptitude',sub:'averages',type:'MCQ',marks:2,diff:'seed',
stem:'The average of the first ten natural numbers is',
opts:['$5.0$','$5.5$','$6.0$','$4.5$'],
ans:1,
sol:'Sum $=10\\times11/2=55$, average $=55/10=5.5$. For $1$ to $n$ the mean is $(n+1)/2$.',tags:['average']},
{id:'PF-CS-A03',n:3,part:'A',lane:'aptitude',sub:'speed-distance',type:'MCQ',marks:2,diff:'seed',
stem:'A $300\\,\\mathrm{m}$ long train crosses a pole in $12\\,\\mathrm{s}$. The speed of the train is',
opts:['$60\\,\\mathrm{km/h}$','$75\\,\\mathrm{km/h}$','$90\\,\\mathrm{km/h}$','$120\\,\\mathrm{km/h}$'],
ans:2,
sol:'Speed $=300/12=25\\,\\mathrm{m/s}=25\\times3.6=90\\,\\mathrm{km/h}$.',tags:['speed']},
{id:'PF-CS-A04',n:4,part:'A',lane:'aptitude',sub:'profit-loss',type:'MCQ',marks:2,diff:'standard',
stem:'An article is sold for Rs. $840$ at a profit of $20\\%$ on the cost price. The cost price is',
opts:['Rs. $700$','Rs. $672$','Rs. $714$','Rs. $750$'],
ans:0,
sol:'$CP=SP/1.2=840/1.2=700$. (Rs. $672$ would follow from wrongly taking $80\\%$ of $840$.)',tags:['percentage']},
{id:'PF-CS-A05',n:5,part:'A',lane:'aptitude',sub:'probability',type:'MCQ',marks:2,diff:'standard',
stem:'Three fair coins are tossed. The probability of getting exactly two heads is',
opts:['$1/4$','$3/8$','$1/2$','$5/8$'],
ans:1,
sol:'Favourable outcomes $\\{HHT,HTH,THH\\}$: $3$ of $2^3=8$, so $P=3/8=0.375$.',tags:['binomial']},
{id:'PF-CS-A06',n:6,part:'A',lane:'aptitude',sub:'coding',type:'MCQ',marks:2,diff:'seed',
stem:'In a code, each letter is shifted one step forward in the alphabet, so CODE becomes DPEF. By the same rule, GATE becomes',
opts:['HBUF','HZUF','GBUF','HBVE'],
ans:0,
sol:'$G\\to H$, $A\\to B$, $T\\to U$, $E\\to F$, giving HBUF.',tags:['letter-shift']},
{id:'PF-CS-A07',n:7,part:'A',lane:'aptitude',sub:'permutations',type:'MCQ',marks:2,diff:'standard',
stem:'The number of ways to arrange $5$ distinct books on a shelf so that $2$ particular books are always adjacent is',
opts:['$24$','$48$','$72$','$120$'],
ans:1,
sol:'Glue the pair into one block: $4!$ arrangements of the block plus three books, times $2!$ inside the block: $24\\times2=48$.',tags:['arrangement']},
{id:'PF-CS-A08',n:8,part:'A',lane:'aptitude',sub:'geometry',type:'MCQ',marks:2,diff:'standard',
stem:'Two similar triangles have corresponding sides in the ratio $3:2$. The ratio of their areas is',
opts:['$3:2$','$9:4$','$27:8$','$6:4$'],
ans:1,
sol:'Areas scale as the square of the length ratio: $3^2:2^2=9:4$.',tags:['similarity']},
{id:'PF-CS-A09',n:9,part:'A',lane:'aptitude',sub:'clocks',type:'MCQ',marks:2,diff:'standard',
stem:'The angle between the hour and minute hands of a clock at $3{:}15$ is',
opts:['$0^\\circ$','$7.5^\\circ$','$15^\\circ$','$30^\\circ$'],
ans:1,
sol:'$|30H-5.5M|=|90-82.5|=7.5^\\circ$: the hour hand has moved a quarter of the way from $3$ toward $4$.',tags:['clock-angle']},
{id:'PF-CS-A10',n:10,part:'A',lane:'aptitude',sub:'series',type:'MCQ',marks:2,diff:'seed',
stem:'The sum $1+2+3+\\cdots+100$ equals',
opts:['$4950$','$5000$','$5050$','$5150$'],
ans:2,
sol:'$n(n+1)/2$ with $n=100$: $100\\times101/2=5050$ (the Gauss pairing trick).',tags:['arithmetic-series']}
]
