/* PAPERFORGE S5 · LEGION CS-I · part 2/7 — PART A (aptitude) Q11-20 · +2 / −0.5
   Original items, authored+re-derived 2026-08-18. Schema as in pfcs_p1.js. */
[
{id:'PF-CS-A11',n:11,part:'A',lane:'aptitude',sub:'boats-streams',type:'MCQ',marks:2,diff:'standard',
stem:'A boatman rows at $6\\,\\mathrm{km/h}$ downstream and $4\\,\\mathrm{km/h}$ upstream on the same river. His rowing speed in still water is',
opts:['$4.5\\,\\mathrm{km/h}$','$5\\,\\mathrm{km/h}$','$5.5\\,\\mathrm{km/h}$','$10\\,\\mathrm{km/h}$'],
ans:1,
sol:'Still-water speed $=(u+d)/2=(6+4)/2=5\\,\\mathrm{km/h}$ (the current is the other half of the difference, $1\\,\\mathrm{km/h}$).',tags:['relative-speed']},
{id:'PF-CS-A12',n:12,part:'A',lane:'aptitude',sub:'percentage',type:'MCQ',marks:2,diff:'standard',
stem:'A number is increased by $20\\%$ and the result is then decreased by $20\\%$. If the original number was $500$, the final number is',
opts:['$500$','$480$','$520$','$460$'],
ans:1,
sol:'Net factor $1.2\\times0.8=0.96$, a net $4\\%$ loss: $500\\times0.96=480$. The operations do not cancel because the bases differ.',tags:['successive-change']},
{id:'PF-CS-A13',n:13,part:'A',lane:'aptitude',sub:'probability',type:'MCQ',marks:2,diff:'standard',
stem:'Two fair dice are thrown. The probability that the sum of the faces is $7$ is',
opts:['$1/6$','$7/36$','$1/9$','$5/36$'],
ans:0,
sol:'Six ordered pairs give sum $7$: $(1,6),(2,5),(3,4),(4,3),(5,2),(6,1)$, so $P=6/36=1/6$.',tags:['dice']},
{id:'PF-CS-A14',n:14,part:'A',lane:'aptitude',sub:'syllogism',type:'MCQ',marks:2,diff:'standard',
stem:'Statements: (i) All physicists are researchers. (ii) Some researchers are poets. Which conclusion necessarily follows?',
opts:['Some researchers are physicists','Some poets are physicists','All poets are researchers','No physicist is a poet'],
ans:0,
sol:'“All physicists are researchers” inverts to “some researchers are physicists”, which must hold in every model. The poet clauses never connect poets to physicists, so the other options can all be false.',tags:['logic']},
{id:'PF-CS-A15',n:15,part:'A',lane:'aptitude',sub:'data-interpretation',type:'MCQ',marks:2,diff:'standard',fig:'ga-bar-chart',
stem:'The chart shows, year-wise, candidates appeared and qualified (in thousands). The qualifying percentage (qualified $\\div$ appeared) was highest in the year',
opts:['$2017$','$2019$','$2021$','$2023$'],
ans:3,
sol:'Ratios: $18/62=29.0\\%$, $22/70=31.4\\%$, $20/58=34.5\\%$, $31/80=38.8\\%$. The maximum is $2023$ despite $2021$ having fewer total candidates.',tags:['bar-chart','ratio']},
{id:'PF-CS-A16',n:16,part:'A',lane:'aptitude',sub:'ages',type:'MCQ',marks:2,diff:'standard',
stem:'A father is three times as old as his son. In $12$ years he will be twice as old as his son. The present age of the son is',
opts:['$8$ years','$10$ years','$12$ years','$16$ years'],
ans:2,
sol:'Let the son be $s$: $3s+12=2(s+12)$ gives $s=12$ (father $36$ now, $48$ then; son $24$ then).',tags:['linear-equation']},
{id:'PF-CS-A17',n:17,part:'A',lane:'aptitude',sub:'work-time',type:'MCQ',marks:2,diff:'standard',
stem:'$A$ can finish a job in $12$ days and $B$ in $6$ days. Working together, they finish it in',
opts:['$3$ days','$4$ days','$6$ days','$8$ days'],
ans:1,
sol:'Rates add: $1/12+1/6=1/12+2/12=3/12=1/4$ of the job per day, hence $4$ days.',tags:['combined-work']},
{id:'PF-CS-A18',n:18,part:'A',lane:'aptitude',sub:'number-series',type:'MCQ',marks:2,diff:'apex',
stem:'Find the next term of the series: $3,\\,7,\\,16,\\,35,\\,74,\\,?$',
opts:['$148$','$153$','$158$','$163$'],
ans:1,
sol:'Each step doubles and adds a growing increment: $\\times2+1,\\times2+2,\\times2+3,\\times2+4$, so next $\\times2+5$: $74\\times2+5=153$.',tags:['series']},
{id:'PF-CS-A19',n:19,part:'A',lane:'aptitude',sub:'series',type:'MCQ',marks:2,diff:'standard',
stem:'The sum of the first $20$ odd natural numbers is',
opts:['$380$','$400$','$420$','$440$'],
ans:1,
sol:'First $n$ odd numbers sum to $n^2$: $20^2=400$. Direct check: $1+3+\\cdots+39=20\\times(1+39)/2=400$.',tags:['odd-numbers']},
{id:'PF-CS-A20',n:20,part:'A',lane:'aptitude',sub:'cubes',type:'MCQ',marks:2,diff:'apex',
stem:'A solid cube is painted on all faces and cut into $64$ equal smaller cubes. The number of smaller cubes with exactly two painted faces is',
opts:['$8$','$16$','$24$','$32$'],
ans:2,
sol:'$64=4^3$ gives $n=4$. Two-face cubes live on edges excluding corners: $12\\times(n-2)=12\\times2=24$. ($8$ corner cubes have three faces painted.)',tags:['spatial']}
]
