/* PAPERFORGE S5 · LEGION CS-I · part 7/7 — PART C (advanced, +5 / −1.25) Q66-75
   Original items, authored+re-derived 2026-08-18. Schema as in pfcs_p1.js. */
[
{id:'PF-CS-C21',n:66,part:'C',lane:'electronics',sub:'bridges',type:'MCQ',marks:5,diff:'standard',
stem:'A Wheatstone bridge has $R_1=1\\,\\mathrm{k\\Omega}$, $R_2=2\\,\\mathrm{k\\Omega}$ in one arm pair and $R_4=6\\,\\mathrm{k\\Omega}$ opposite to the unknown $R_3$. The value of $R_3$ that balances the bridge is',
opts:['$1.5\\,\\mathrm{k\\Omega}$','$3\\,\\mathrm{k\\Omega}$','$6\\,\\mathrm{k\\Omega}$','$12\\,\\mathrm{k\\Omega}$'],
ans:1,
sol:'Balance condition $R_1/R_2=R_3/R_4$: $R_3=R_4\\times R_1/R_2=6\\times1/2=3\\,\\mathrm{k\\Omega}$.',tags:['wheatstone']},
{id:'PF-CS-C22',n:67,part:'C',lane:'electronics',sub:'opamp',type:'MCQ',marks:5,diff:'standard',
stem:'An op-amp has a gain–bandwidth product of $1\\,\\mathrm{MHz}$. Wired as a non-inverting amplifier with closed-loop gain $100$, its small-signal bandwidth is',
opts:['$1\\,\\mathrm{kHz}$','$10\\,\\mathrm{kHz}$','$100\\,\\mathrm{kHz}$','$1\\,\\mathrm{MHz}$'],
ans:1,
sol:'$GBW=A_{CL}\\times f_{-3dB}$ is constant for dominant-pole roll-off: $f=1\\,\\mathrm{MHz}/100=10\\,\\mathrm{kHz}$.',tags:['gain-bandwidth']},
{id:'PF-CS-C23',n:68,part:'C',lane:'atnuc',sub:'semf',type:'MCQ',marks:5,diff:'apex',fig:'nu-semf-curve',
stem:'In the semi-empirical mass formula (curve sketched in the figure), the Coulomb term is $-a_cZ^2A^{-1/3}$ with $a_c=0.7\\,\\mathrm{MeV}$. Its magnitude for $^{40}$Ca ($Z=20$, $A=40$) is closest to',
opts:['$41\\,\\mathrm{MeV}$','$82\\,\\mathrm{MeV}$','$112\\,\\mathrm{MeV}$','$164\\,\\mathrm{MeV}$'],
ans:1,
sol:'$a_cZ^2A^{-1/3}=0.7\\times400/40^{1/3}=280/3.42=81.9\\,\\mathrm{MeV}\\approx82\\,\\mathrm{MeV}$ — the repulsion driving the curve down at large $A$.',tags:['liquid-drop']},
{id:'PF-CS-C24',n:69,part:'C',lane:'atnuc',sub:'radioactivity',type:'MCQ',marks:5,diff:'apex',
stem:'The activity of $1\\,\\mathrm{mg}$ of $^{24}$Na (half-life $15\\,\\mathrm{h}$), is closest to',
opts:['$3.2\\times10^{12}\\,\\mathrm{Bq}$','$8.0\\times10^{13}\\,\\mathrm{Bq}$','$1.6\\times10^{14}\\,\\mathrm{Bq}$','$3.2\\times10^{14}\\,\\mathrm{Bq}$'],
ans:3,
sol:'$N=10^{-3}/24\\times6.022\\times10^{23}=2.51\\times10^{19}$, $\\lambda=\\ln2/(15\\times3600)=1.28\\times10^{-5}\\,\\mathrm{s^{-1}}$, so $A=\\lambda N=3.2\\times10^{14}\\,\\mathrm{Bq}$.',tags:['activity']},
{id:'PF-CS-C25',n:70,part:'C',lane:'solidstate',sub:'fermi-gas',type:'MCQ',marks:5,diff:'standard',
stem:'A metal has Fermi energy $E_F=5\\,\\mathrm{eV}$. Its Fermi temperature $T_F=E_F/k_B$ is closest to',
opts:['$5.8\\times10^{2}\\,\\mathrm{K}$','$5.8\\times10^{3}\\,\\mathrm{K}$','$5.8\\times10^{4}\\,\\mathrm{K}$','$5.8\\times10^{5}\\,\\mathrm{K}$'],
ans:2,
sol:'$T_F=5\\,\\mathrm{eV}/(8.617\\times10^{-5}\\,\\mathrm{eV/K})=5.8\\times10^{4}\\,\\mathrm{K}$ — far above melting, which is why $T\\ll T_F$ degeneracy holds in metals.',tags:['degeneracy']},
{id:'PF-CS-C26',n:71,part:'C',lane:'solidstate',sub:'crystal-structure',type:'MCQ',marks:5,diff:'standard',
stem:'The coordination number (number of nearest neighbours of an atom) in the face-centred cubic structure is',
opts:['$6$','$8$','$12$','$14$'],
ans:2,
sol:'Each FCC atom touches $12$ face-diagonal neighbours ($4$ in its own plane layer, $4$ above, $4$ below); $8$ is BCC and $6$ simple cubic.',tags:['coordination']},
{id:'PF-CS-C27',n:72,part:'C',lane:'solidstate',sub:'effective-mass',type:'MCQ',marks:5,diff:'apex',
stem:'Near the bottom of a band the dispersion is $E(k)=E_0+\\alpha k^2$ with $\\alpha=1.0\\times10^{-38}\\,\\mathrm{J\\,m^2}$. The effective mass $m^*=\\hbar^2/(d^2E/dk^2)$ is',
opts:['$1.1\\times10^{-31}\\,\\mathrm{kg}$','$5.6\\times10^{-31}\\,\\mathrm{kg}$','$1.1\\times10^{-30}\\,\\mathrm{kg}$','$2.2\\times10^{-30}\\,\\mathrm{kg}$'],
ans:1,
sol:'$d^2E/dk^2=2\\alpha$, so $m^*=\\hbar^2/(2\\alpha)=(1.055\\times10^{-34})^2/(2\\times10^{-38})=1.113\\times10^{-68}/(2\\times10^{-38})=5.6\\times10^{-31}\\,\\mathrm{kg}$.',tags:['band-curvature']},
{id:'PF-CS-C28',n:73,part:'C',lane:'solidstate',sub:'diffraction',type:'MCQ',marks:5,diff:'standard',
stem:'X-rays of wavelength $1.0\\,\\text{\\AA}$ show a second-order Bragg reflection from a set of planes at $\\theta=30^\\circ$. The interplanar spacing is',
opts:['$1.0\\,\\text{\\AA}$','$2.0\\,\\text{\\AA}$','$4.0\\,\\text{\\AA}$','$0.5\\,\\text{\\AA}$'],
ans:1,
sol:'$n\\lambda=2d\\sin\\theta$ with $n=2$: $d=2\\times1.0/(2\\sin30^\\circ)=2/(2\\times0.5)=2.0\\,\\text{\\AA}$.',tags:['bragg-law']},
{id:'PF-CS-C29',n:74,part:'C',lane:'electronics',sub:'digital',type:'MCQ',marks:5,diff:'standard',
stem:'A JK flip-flop is wired with $J=K=1$. On every active clock edge, its output $Q$',
opts:['stays fixed at $0$','stays fixed at $1$','toggles to its complement','follows the clock waveform exactly'],
ans:2,
sol:'$J=K=1$ is the toggle mode: $Q_{next}=\\bar Q$ each active edge — the basic divide-by-two cell of ripple counters.',tags:['flip-flops']},
{id:'PF-CS-C30',n:75,part:'C',lane:'thermo',sub:'kinetic-theory',type:'MCQ',marks:5,diff:'standard',
stem:'The rms speed of $\\mathrm{O_2}$ molecules (molar mass $0.032\\,\\mathrm{kg/mol}$) at $T=300\\,\\mathrm{K}$ is closest to',
opts:['$279\\,\\mathrm{m/s}$','$342\\,\\mathrm{m/s}$','$484\\,\\mathrm{m/s}$','$968\\,\\mathrm{m/s}$'],
ans:2,
sol:'$v_{rms}=\\sqrt{3RT/M}=\\sqrt{3\\times8.314\\times300/0.032}=\\sqrt{2.338\\times10^{5}}=484\\,\\mathrm{m/s}$.',tags:['maxwell-distribution']}
]
