/* PAPERFORGE S6 · ORACLE GA set A — GATE General Aptitude, 10 originals
   (GA1-5 = 1 mark verbal/numeric-ability, GA6-10 = 2 marks). Same double-solve
   discipline; audited in audit_oracle.py. Schema as in pf2_p1.js. */
[
{id:'PF-GA-A1',n:1,lane:'aptitude',sub:'vocabulary',type:'MCQ',marks:1,diff:'seed',
stem:'Choose the word closest in meaning to CANDID:',
opts:['frank','timid','deceitful','arrogant'],
ans:0,
sol:'CANDID means truthful and straightforward — frank. Deceitful is a near-antonym; timid and arrogant describe unrelated traits.',tags:['synonym']},
{id:'PF-GA-A2',n:2,lane:'aptitude',sub:'grammar',type:'MCQ',marks:1,diff:'standard',
stem:'Neither of the two solutions ______ satisfactory.',
opts:['were','was','are','have been'],
ans:1,
sol:'“Neither” is singular: “neither of … was satisfactory”. The proximity of the plural noun “solutions” is a distractor.',tags:['subject-verb-agreement']},
{id:'PF-GA-A3',n:3,lane:'aptitude',sub:'idioms',type:'MCQ',marks:1,diff:'seed',
stem:'The idiom “to burn the midnight oil” means',
opts:['to work or study late into the night','to waste fuel carelessly','to quarrel until late at night','to wake up very early'],
ans:0,
sol:'Burning midnight oil refers to working or studying by lamp-light, i.e. late into the night.',tags:['idiom']},
{id:'PF-GA-A4',n:4,lane:'aptitude',sub:'letter-series',type:'MCQ',marks:1,diff:'standard',
stem:'Find the next letter in the series: A, C, F, J, O, ?',
opts:['S','T','U','V'],
ans:2,
sol:'Positions $1,3,6,10,15$ are triangular numbers with gaps $+2,+3,+4,+5$; next gap $+6$ gives position $21=$ U.',tags:['series']},
{id:'PF-GA-A5',n:5,lane:'aptitude',sub:'analogy',type:'MCQ',marks:1,diff:'standard',
stem:'OAR : ROW ::  ?',
opts:['PEN : WRITE','BOOK : READ','WHEEL : DRIVE','KNIFE : CUT BREAD'],
ans:0,
sol:'Instrument-to-action relation: one rows with an oar as one writes with a pen. BOOK and WHEEL invert or mismatch the relation.',tags:['analogy']},
{id:'PF-GA-A6',n:6,lane:'aptitude',sub:'percentage',type:'MCQ',marks:2,diff:'standard',
stem:'A town’s population, $10000$ a year ago, grows at $10\\%$ per year (compounded annually). Its present population is',
opts:['$11000$','$12000$','$12100$','$12200$'],
ans:2,
sol:'$10000\\times1.1^2=12100$. The naive linear answer $12000$ ignores compounding in the second year.',tags:['compound-growth']},
{id:'PF-GA-A7',n:7,lane:'aptitude',sub:'speed-distance',type:'MCQ',marks:2,diff:'standard',
stem:'A $240\\,\\mathrm{m}$ long train running at $54\\,\\mathrm{km/h}$ crosses a platform in $30\\,\\mathrm{s}$. The length of the platform is',
opts:['$180\\,\\mathrm{m}$','$210\\,\\mathrm{m}$','$240\\,\\mathrm{m}$','$450\\,\\mathrm{m}$'],
ans:1,
sol:'Speed $=54/3.6=15\\,\\mathrm{m/s}$; distance in $30\\,\\mathrm{s}$ is $450\\,\\mathrm{m}=$ train $+$ platform, so platform $=450-240=210\\,\\mathrm{m}$.',tags:['trains']},
{id:'PF-GA-A8',n:8,lane:'aptitude',sub:'probability',type:'MCQ',marks:2,diff:'apex',
stem:'A box holds $4$ red and $6$ blue balls. Two balls are drawn together at random. The probability that both are red is',
opts:['$1/5$','$4/25$','$2/15$','$1/6$'],
ans:2,
sol:'$P=\\binom{4}{2}/\\binom{10}{2}=6/45=2/15$ (equivalently $(4/10)(3/9)$). With-replacement would give $4/25$.',tags:['combinatorics']},
{id:'PF-GA-A9',n:9,lane:'aptitude',sub:'averages',type:'MCQ',marks:2,diff:'standard',
stem:'The average of $5$ numbers is $20$. When one number is removed, the average of the remaining four falls to $18$. The removed number is',
opts:['$22$','$24$','$28$','$32$'],
ans:2,
sol:'Total $=100$; after removal $4\\times18=72$; removed $=100-72=28$.',tags:['average']},
{id:'PF-GA-A10',n:10,lane:'aptitude',sub:'geometry',type:'MCQ',marks:2,diff:'seed',
stem:'The diagonal of a rectangle with sides $12\\,\\mathrm{cm}$ and $9\\,\\mathrm{cm}$ is',
opts:['$13\\,\\mathrm{cm}$','$14\\,\\mathrm{cm}$','$15\\,\\mathrm{cm}$','$21\\,\\mathrm{cm}$'],
ans:2,
sol:'$\\sqrt{12^2+9^2}=\\sqrt{144+81}=\\sqrt{225}=15\\,\\mathrm{cm}$ — the $9{:}12{:}15=3{:}4{:}5$ triple.',tags:['pythagoras']}
]
