/* PAPERFORGE S6 · ORACLE GA set B — GATE General Aptitude, 10 originals
   (GA1-5 = 1 mark, GA6-10 = 2 marks). Schema as in pfga_a.js. */
[
{id:'PF-GA-B1',n:1,lane:'aptitude',sub:'vocabulary',type:'MCQ',marks:1,diff:'seed',
stem:'Choose the word most nearly OPPOSITE in meaning to OPAQUE:',
opts:['cloudy','transparent','brittle','dull'],
ans:1,
sol:'OPAQUE blocks light; its antonym is transparent. Cloudy is a weaker synonym, brittle and dull are unrelated.',tags:['antonym']},
{id:'PF-GA-B2',n:2,lane:'aptitude',sub:'grammar',type:'MCQ',marks:1,diff:'standard',
stem:'Each of the boys ______ given a prize at the function.',
opts:['were','was','have been','are'],
ans:1,
sol:'“Each (of …)” takes a singular verb: “was given”. The plural noun “boys” between subject and verb is the classic distractor.',tags:['subject-verb-agreement']},
{id:'PF-GA-B3',n:3,lane:'aptitude',sub:'idioms',type:'MCQ',marks:1,diff:'seed',
stem:'“A blessing in disguise” refers to',
opts:['a benefit that first appears as a misfortune','a religious ceremony in plain clothes','a gift given anonymously','an unexpected visit from a friend'],
ans:0,
sol:'The idiom names a good outcome hidden inside something that looked bad at first — a hidden benefit.',tags:['idiom']},
{id:'PF-GA-B4',n:4,lane:'aptitude',sub:'odd-one-out',type:'MCQ',marks:1,diff:'standard',
stem:'Find the odd one out: $121,\\ 144,\\ 169,\\ 225,\\ 275$',
opts:['$144$','$169$','$225$','$275$'],
ans:3,
sol:'$121=11^2$, $144=12^2$, $169=13^2$, $225=15^2$ are perfect squares; $275$ is not a square.',tags:['squares']},
{id:'PF-GA-B5',n:5,lane:'aptitude',sub:'sentence-completion',type:'MCQ',marks:1,diff:'standard',
stem:'Despite the evidence against him, he continued to ______ his innocence.',
opts:['deny','maintain','confound','surrender'],
ans:1,
sol:'The standard collocation is “maintain one’s innocence”. “Deny his innocence” reverses the sense; “confound” and “surrender” break the idiom.',tags:['collocation']},
{id:'PF-GA-B6',n:6,lane:'aptitude',sub:'interest',type:'MCQ',marks:2,diff:'standard',
stem:'A sum of money doubles itself in $8$ years at simple interest. The annual rate of interest is',
opts:['$10\\%$','$12\\%$','$12.5\\%$','$25\\%$'],
ans:2,
sol:'Doubling needs interest $=P$ in $8$ years: $r=P\\times100/(P\\times8)=12.5\\%$ per annum.',tags:['simple-interest']},
{id:'PF-GA-B7',n:7,lane:'aptitude',sub:'work-time',type:'MCQ',marks:2,diff:'seed',
stem:'$6$ men can complete a piece of work in $10$ days. Working at the same rate, $4$ men will complete it in',
opts:['$12$ days','$15$ days','$18$ days','$6.7$ days'],
ans:1,
sol:'Man-days are constant: $6\\times10=60$, so $60/4=15$ days.',tags:['inverse-proportion']},
{id:'PF-GA-B8',n:8,lane:'aptitude',sub:'mixtures',type:'MCQ',marks:2,diff:'apex',
stem:'A $40$-litre mixture has milk and water in the ratio $5:3$. How much water must be added to make the ratio $1:1$?',
opts:['$8$ litres','$10$ litres','$12$ litres','$15$ litres'],
ans:1,
sol:'Milk $=25$ L, water $=15$ L. For $1:1$ the water must reach $25$ L, so add $10$ litres (milk is untouched).',tags:['ratio']},
{id:'PF-GA-B9',n:9,lane:'aptitude',sub:'probability',type:'MCQ',marks:2,diff:'standard',
stem:'Two fair dice are rolled. The probability that the sum of the numbers shown is at least $10$ is',
opts:['$1/12$','$1/9$','$1/6$','$1/4$'],
ans:2,
sol:'Sums $10,11,12$ come from $3+2+1=6$ ordered pairs, so $P=6/36=1/6$.',tags:['dice']},
{id:'PF-GA-B10',n:10,lane:'aptitude',sub:'numbers',type:'MCQ',marks:2,diff:'apex',
stem:'If $x=3^{40}$ and $y=4^{30}$, then',
opts:['$x<y$','$x=y$','$x>y$','the two cannot be compared without computing them'],
ans:2,
sol:'$x=(3^4)^{10}=81^{10}$ and $y=(4^3)^{10}=64^{10}$; equal exponents make $81^{10}>64^{10}$, so $x>y$.',tags:['exponents']}
]
