/* PAPERFORGE S6 · ORACLE GA set C — GATE General Aptitude, 10 originals
   (GA1-5 = 1 mark, GA6-10 = 2 marks). Schema as in pfga_a.js. */
[
{id:'PF-GA-C1',n:1,lane:'aptitude',sub:'vocabulary',type:'MCQ',marks:1,diff:'standard',
stem:'Choose the word closest in meaning to EPHEMERAL:',
opts:['eternal','short-lived','fragile','artificial'],
ans:1,
sol:'EPHEMERAL means lasting a very short time — short-lived (from the mayfly genus Ephemera). Eternal is the antonym.',tags:['synonym']},
{id:'PF-GA-C2',n:2,lane:'aptitude',sub:'grammar',type:'MCQ',marks:1,diff:'apex',
stem:'Neither the teacher nor the students ______ present in the hall.',
opts:['was','were','is','has been'],
ans:1,
sol:'With “neither … nor”, the verb agrees with the nearer subject; “the students” is plural, so “were”.',tags:['proximity-agreement']},
{id:'PF-GA-C3',n:3,lane:'aptitude',sub:'idioms',type:'MCQ',marks:1,diff:'seed',
stem:'“To hit the nail on the head” means',
opts:['to strike hard in anger','to say exactly the right thing','to finish work ahead of time','to take an unnecessary risk'],
ans:1,
sol:'The idiom means describing a situation or answer with perfect accuracy — saying exactly the right thing.',tags:['idiom']},
{id:'PF-GA-C4',n:4,lane:'aptitude',sub:'number-series',type:'MCQ',marks:1,diff:'standard',
stem:'Find the next term of the series: $2,\\,3,\\,5,\\,9,\\,17,\\,?$',
opts:['$31$','$32$','$33$','$34$'],
ans:2,
sol:'Each term doubles the previous and subtracts $1$: $2\\to3\\to5\\to9\\to17$, so $17\\times2-1=33$. (Equivalently gaps double: $+1,+2,+4,+8$, then $+16$.)',tags:['series']},
{id:'PF-GA-C5',n:5,lane:'aptitude',sub:'analogy',type:'MCQ',marks:1,diff:'seed',
stem:'DOCTOR : PATIENT ::  ?',
opts:['LAWYER : CLIENT','SHOPKEEPER : SHOP','TEACHER : BOOK','FARMER : HARVEST'],
ans:0,
sol:'Professional-to-served-person relation: a doctor serves a patient as a lawyer serves a client.',tags:['analogy']},
{id:'PF-GA-C6',n:6,lane:'aptitude',sub:'speed-distance',type:'MCQ',marks:2,diff:'standard',
stem:'A cyclist covers a certain distance at $60\\,\\mathrm{km/h}$ and returns along the same route at $40\\,\\mathrm{km/h}$. The average speed for the whole journey is',
opts:['$45\\,\\mathrm{km/h}$','$48\\,\\mathrm{km/h}$','$50\\,\\mathrm{km/h}$','$52\\,\\mathrm{km/h}$'],
ans:1,
sol:'Equal distances take the harmonic mean: $\\bar v=2\\times60\\times40/(60+40)=4800/100=48\\,\\mathrm{km/h}$, not the arithmetic $50$.',tags:['average-speed']},
{id:'PF-GA-C7',n:7,lane:'aptitude',sub:'percentage',type:'MCQ',marks:2,diff:'standard',
stem:'A number exceeds $25\\%$ of itself by $45$. The number is',
opts:['$50$','$60$','$75$','$90$'],
ans:1,
sol:'$x-0.25x=45$ gives $0.75x=45$, so $x=60$. ($25\\%$ of $60$ is $15$, and $60-15=45$ ✓.)',tags:['percentage']},
{id:'PF-GA-C8',n:8,lane:'aptitude',sub:'combinatorics',type:'MCQ',marks:2,diff:'apex',
stem:'A committee of $3$ is to be formed from $5$ men and $4$ women so that exactly $2$ members are men. The number of ways is',
opts:['$30$','$40$','$60$','$84$'],
ans:1,
sol:'$\\binom{5}{2}\\times\\binom{4}{1}=10\\times4=40$. ($84=\\binom{9}{3}$ ignores the gender condition.)',tags:['combinations']},
{id:'PF-GA-C9',n:9,lane:'aptitude',sub:'clocks',type:'MCQ',marks:2,diff:'standard',
stem:'The angle between the hour and minute hands of a clock at $6{:}30$ is',
opts:['$0^\\circ$','$15^\\circ$','$30^\\circ$','$7.5^\\circ$'],
ans:1,
sol:'$|30H-5.5M|=|180-165|=15^\\circ$: the hour hand has drifted halfway from $6$ to $7$.',tags:['clock-angle']},
{id:'PF-GA-C10',n:10,lane:'aptitude',sub:'series',type:'MCQ',marks:2,diff:'standard',
stem:'The sum $1^2+2^2+3^2+\\cdots+10^2$ equals',
opts:['$375$','$385$','$395$','$495$'],
ans:1,
sol:'$\\sum k^2=n(n+1)(2n+1)/6$ with $n=10$: $10\\times11\\times21/6=2310/6=385$.',tags:['square-sum']}
]
