/* Round 10 apply: GameForge masters + surgical hooks into the base theme-games code.
   Every surgical pair is asserted to occur EXACTLY once; the old/new strings are archived
   in _audit/surgical_r10.json so the insertion verifier can revert them byte-exactly. */
const fs = require('fs');
const P = '/home/user/project/CSIR_GATE_Tracker_Physics_Lab_edited (3).html';
let doc = fs.readFileSync(P, 'utf8');
const origLen = doc.length;

const PAIRS = [];
const pair = (name, oldS, newS) => PAIRS.push({name, old: oldS, new: newS});

/* ---- Equation Sprint ---- */
pair('eq-arena: pace/readout row',
  `setArena('<div id="equationQuestion" class="equation-question"></div><div id="equationOptions" class="equation-options"></div>');`,
  `setArena('<div class="equation-topline"><span id="equationPace" class="equation-pace"></span></div><div id="equationQuestion" class="equation-question"></div><div id="equationOptions" class="equation-options"></div>');`);

pair('eq-bank: GameForge queue w/ original fallback',
  `const qs=gameLevel==='noobie'?base:gameLevel==='adept'?base.concat(hard.slice(0,2)):gameLevel==='elite'?base.concat(hard.slice(0,4)):base.concat(hard);`,
  `const qs=(window.GameForge&&window.GameForge.equationQueue)?window.GameForge.equationQueue(gameLevel,base,hard):(gameLevel==='noobie'?base:gameLevel==='adept'?base.concat(hard.slice(0,2)):gameLevel==='elite'?base.concat(hard.slice(0,4)):base.concat(hard));`);

pair('eq-draw: badge + per-question pace timer + refill poke',
  `    function draw(){const q=qs[index%qs.length];qEl.textContent=q.q;oEl.innerHTML='';q.o.forEach((x,i)=>{const b=document.createElement('button');b.className='equation-option';b.textContent=x;b.addEventListener('click',()=>{if(!gameActive)return;if(i===q.a){b.classList.add('good');setScore(score+15+(gameLevel==='godhood'?8:0));setStatus('Correct · next equation.');}else{b.classList.add('bad');setStatus('Not quite · keep the model clean.');}setTimeout(()=>{index++;draw();},330);});oEl.appendChild(b);});}`,
  `    function draw(){
      const q=qs[index%qs.length];
      if(window.GameForge)window.GameForge.equationPoke(qs,index,gameLevel);
      qEl.innerHTML=(q&&q.ai?'<span class="gf-ai-badge" title="Generated by your configured AI provider">\\u2726 AI-GENERATED</span>':'')+escapeHtml(q.q);
      oEl.innerHTML='';q.o.forEach((x,i)=>{const b=document.createElement('button');b.className='equation-option';b.textContent=x;b.addEventListener('click',()=>{if(!gameActive)return;clearInterval(window.__gfEqTimer);if(i===q.a){b.classList.add('good');setScore(score+15+(gameLevel==='godhood'?8:0));setStatus('Correct · next equation.');}else{b.classList.add('bad');setStatus('Not quite · keep the model clean.');}setTimeout(()=>{index++;draw();},330);});oEl.appendChild(b);});
      const paceSecs=(window.GameForge&&window.GameForge.equationPace)?window.GameForge.equationPace(gameLevel):0;
      const paceEl=document.getElementById('equationPace');
      clearInterval(window.__gfEqTimer);window.__gfEqTimer=null;
      if(paceEl){
        if(paceSecs>0){let left=paceSecs;paceEl.textContent='\\u23F1 '+left+'s · '+gameLevel.toUpperCase();paceEl.className='equation-pace hot';
          window.__gfEqTimer=setInterval(()=>{if(!gameActive){clearInterval(window.__gfEqTimer);window.__gfEqTimer=null;return;}left--;paceEl.textContent='\\u23F1 '+left+'s · '+gameLevel.toUpperCase();if(left<=0){clearInterval(window.__gfEqTimer);window.__gfEqTimer=null;setStatus('Time up · '+gameLevel.toUpperCase()+' pace is unforgiving. Next equation.');index++;draw();}},1000);
        }else{paceEl.textContent=gameLevel.toUpperCase()+' · relaxed pace';paceEl.className='equation-pace';}
      }
    }`);

pair('eq-status: forge status line',
  `    draw();setStatus('Choose the correct result · '+cfg.label+' bank loaded.');`,
  `    draw();setStatus(window.GameForge?window.GameForge.equationStatus(qs,gameLevel):('Choose the correct result · '+cfg.label+' bank loaded.'));`);

/* ---- Gravitational Slingshot ---- */
pair('grav-levels: 60 sectors w/ original-5 fallback',
`    const challenges=[
      {name:'FIRST ASSIST',start:[.13,.72],goal:[.84,.25],planets:[{x:.50,y:.52,r:22,m:1.1,c:'#72dfff'}]},
      {name:'LAGRANGE TURN',start:[.12,.76],goal:[.86,.24],planets:[{x:.44,y:.48,r:22,m:1.2,c:'#77e6ff'},{x:.68,y:.63,r:15,m:.7,c:'#c4ff72'}]},
      {name:'DOUBLE SLING',start:[.12,.78],goal:[.88,.22],planets:[{x:.36,y:.55,r:19,m:1.2,c:'#a78bff'},{x:.64,y:.46,r:23,m:1.35,c:'#ffe19a'}]},
      {name:'NEUTRON PASS',start:[.10,.70],goal:[.88,.32],planets:[{x:.47,y:.44,r:27,m:1.7,c:'#ff8e9e'},{x:.71,y:.70,r:13,m:.5,c:'#78e5ff'}]},
      {name:'BLACK-HOLE GATE',start:[.10,.82],goal:[.90,.18],planets:[{x:.50,y:.50,r:31,m:2.5,c:'#a88cff'},{x:.28,y:.32,r:12,m:.55,c:'#ffe19a'},{x:.73,y:.70,r:12,m:.55,c:'#79e6ff'}]}
    ];`,
`    const challenges=(window.GameForge&&window.GameForge.gravityLevels)?window.GameForge.gravityLevels():[
      {name:'FIRST ASSIST',start:[.13,.72],goal:[.84,.25],planets:[{x:.50,y:.52,r:22,m:1.1,c:'#72dfff'}]},
      {name:'LAGRANGE TURN',start:[.12,.76],goal:[.86,.24],planets:[{x:.44,y:.48,r:22,m:1.2,c:'#77e6ff'},{x:.68,y:.63,r:15,m:.7,c:'#c4ff72'}]},
      {name:'DOUBLE SLING',start:[.12,.78],goal:[.88,.22],planets:[{x:.36,y:.55,r:19,m:1.2,c:'#a78bff'},{x:.64,y:.46,r:23,m:1.35,c:'#ffe19a'}]},
      {name:'NEUTRON PASS',start:[.10,.70],goal:[.88,.32],planets:[{x:.47,y:.44,r:27,m:1.7,c:'#ff8e9e'},{x:.71,y:.70,r:13,m:.5,c:'#78e5ff'}]},
      {name:'BLACK-HOLE GATE',start:[.10,.82],goal:[.90,.18],planets:[{x:.50,y:.50,r:31,m:2.5,c:'#a88cff'},{x:.28,y:.32,r:12,m:.55,c:'#ffe19a'},{x:.73,y:.70,r:12,m:.55,c:'#79e6ff'}]}
    ];`);

pair('grav-attempts-init',
  `;let attempts=3;`,
  `;let attempts=(window.GameForge?window.GameForge.gravityRules(gameLevel).attempts:3);`);

pair('grav-pull: difficulty-scaled gravity',
  `,c=cfg(),G=7800;`,
  `,c=cfg(),G=7800*(window.GameForge?window.GameForge.gravityRules(gameLevel,c).pull:1);`);

pair('grav-gate: difficulty+sector scaled dock radius',
  `if(Math.hypot(ship.x-gx,ship.y-gy)<28){`,
  `if(Math.hypot(ship.x-gx,ship.y-gy)<28*(window.GameForge?window.GameForge.gravityRules(gameLevel,c).gate:1)){`);

pair('grav-reset: rules-based attempts',
  `reset.addEventListener('click',()=>{gameActive=true;attempts=3;resetFlight();`,
  `reset.addEventListener('click',()=>{gameActive=true;attempts=(window.GameForge?window.GameForge.gravityRules(gameLevel,cfg()).attempts:3);resetFlight();`);

pair('grav-next: dynamic total + sector name + rules attempts',
  `attempts=3;document.getElementById('gravityChallenge').textContent=(challenge+1)+'/5';resetFlight();`,
  `attempts=(window.GameForge?window.GameForge.gravityRules(gameLevel,cfg()).attempts:3);document.getElementById('gravityChallenge').textContent=(challenge+1)+'/'+challenges.length;const gsN=document.getElementById('gravitySector');if(gsN)gsN.textContent=cfg().name||'';resetFlight();`);

pair('grav-hud-init: dynamic total + sector name',
  `size();document.getElementById('gravityChallenge').textContent='1/5';resetFlight();`,
  `size();document.getElementById('gravityChallenge').textContent='1/'+challenges.length;const gs0=document.getElementById('gravitySector');if(gs0)gs0.textContent=cfg().name||'';resetFlight();`);

pair('grav-hud-html: sector label slot',
  `<span>CHALLENGE <b id="gravityChallenge">1/5</b></span>`,
  `<span>CHALLENGE <b id="gravityChallenge">1/5</b></span><span class="gravity-sector" id="gravitySector"></span>`);

pair('grav-log: sector intel appended',
  `log.textContent='Drag from the ship opposite to your desired launch direction.';draw();}`,
  `log.textContent='Drag from the ship opposite to your desired launch direction.'+(window.GameForge&&cfg().twistNote?' · '+cfg().twistNote:'');draw();}`);

/* ---- run surgical pairs ---- */
const manifest = [];
for (const p of PAIRS){
  const n = doc.split(p.old).length - 1;
  if (n !== 1){ console.error('PAIR FAIL [' + p.name + ']: found ' + n + ' occurrence(s), need exactly 1'); process.exit(1); }
  doc = doc.replace(p.old, () => p.new);
  manifest.push({name: p.name, old: p.old, new: p.new});
  console.log('  ✔ ' + p.name + ' (' + p.old.length + ' → ' + p.new.length + ' chars)');
}

/* ---- append GameForge CSS after ins8 css ---- */
const css = fs.readFileSync('/home/user/_audit/ins9_css.css', 'utf8').replace(/\s+$/, '');
const css8 = fs.readFileSync('/home/user/_audit/ins8_css.css', 'utf8');
const anchor = css8.replace(/\s+$/, '').slice(-60);
if (doc.split(anchor).length - 1 !== 1){ console.error('CSS anchor not unique'); process.exit(1); }
doc = doc.replace(anchor, () => anchor + '\n\n' + css);
console.log('  ✔ ins9_css appended (' + css.length + ' chars)');

/* ---- append GameForge JS before </body> ---- */
const js = fs.readFileSync('/home/user/_audit/ins9_js.js', 'utf8').replace(/\s+$/, '');
if (doc.split('</body>').length - 1 !== 1){ console.error('body close not unique'); process.exit(1); }
doc = doc.replace('</body>', () => '\n<script>\n' + js + '\n\n</script>\n</body>');
console.log('  ✔ ins9_js appended (' + js.length + ' chars)');

fs.writeFileSync(P, doc, 'utf8');
fs.writeFileSync('/home/user/_audit/surgical_r10.json', JSON.stringify({round: 10, note: 'GameForge surgical hooks into base theme-games; verifier reverts these new→old after stripping insertion blocks.', pairs: manifest}, null, 1));
console.log('\nwritten: ' + origLen + ' → ' + doc.length + ' chars | manifest: _audit/surgical_r10.json (' + manifest.length + ' pairs)');
