/* TOPICFORGE T0 — mined lane/subtopic map (generated by _audit/topicforge_mine.js, 2026-08-14)
   Read-only data: the panel scaffold renders this at T0; problems forge at T1+. */
window.TOPICFORGE_MAP = {
 "meta": {
  "op": "TOPICFORGE T0 — THE MAP",
  "version": "T0",
  "generated": "2026-08-14",
  "universe": {
   "total": 1624,
   "csir": 930,
   "gate": 694,
   "csirSessions": [
    "dec2025",
    "jun2021",
    "jul2025",
    "dec2019",
    "june2018",
    "dec2024",
    "dec2018",
    "dec2023",
    "june2023",
    "sep2022",
    "june2020",
    "june2024"
   ],
   "gateSessions": [
    "gate2016",
    "gate2024",
    "gate2025",
    "gate2020",
    "gate2017",
    "gate2018",
    "gate2019",
    "gate2021",
    "gate2022",
    "gate2023",
    "gate2026"
   ],
   "gaTotal": 324,
   "physicsTotal": 1300,
   "unclassCsir": 210,
   "unclassGate": 115
  },
  "classifiedPct": 80,
  "assumptions": [
   "Part A (both exams) routes to the General Aptitude lane; everything else routes to the 9 physics lanes.",
   "Difficulty proxy (documented, not claimed exact): CSIR Part C = apex, Part B = standard; GATE 2-mark = standard, 1-mark = seed; CSIR Part A / GATE GA baseline = standard/seed by marks.",
   "Subtopic assignment is LANE-FIRST: lane = max total rule hits, subtopic = best rule inside that lane; ties resolve to the earlier lane in the canonical order.",
   "Zero-hit questions are COUNTED, not hidden (see unclassified); zero-hit subtopics are demoted to meta.emptySubs (still on the T1 coverage checklist).",
   "Concept-drill roster rule: concept matches ≥3 DISTINCT exam sessions across either exam (exam-agnostic per plan).",
   "Mining only — zero problems forged. T1 pilot awaits map approval."
  ]
 },
 "lanes": [
  {
   "id": "mathphys",
   "title": "Mathematical Physics",
   "total": 185,
   "rows": [
    {
     "id": "linear-algebra",
     "hits": 58,
     "csir": 34,
     "gate": 24,
     "sessions": 23,
     "diff": {
      "seed": 18,
      "standard": 32,
      "apex": 8
     }
    },
    {
     "id": "probability",
     "hits": 50,
     "csir": 37,
     "gate": 13,
     "sessions": 18,
     "diff": {
      "seed": 5,
      "standard": 25,
      "apex": 20
     }
    },
    {
     "id": "complex-analysis",
     "hits": 21,
     "csir": 9,
     "gate": 12,
     "sessions": 16,
     "diff": {
      "seed": 7,
      "standard": 12,
      "apex": 2
     }
    },
    {
     "id": "ode-pde",
     "hits": 21,
     "csir": 16,
     "gate": 5,
     "sessions": 13,
     "diff": {
      "seed": 4,
      "standard": 7,
      "apex": 10
     }
    },
    {
     "id": "fourier-laplace",
     "hits": 10,
     "csir": 6,
     "gate": 4,
     "sessions": 9,
     "diff": {
      "seed": 3,
      "standard": 4,
      "apex": 3
     }
    },
    {
     "id": "vector-calculus",
     "hits": 8,
     "csir": 3,
     "gate": 5,
     "sessions": 7,
     "diff": {
      "seed": 4,
      "standard": 3,
      "apex": 1
     }
    },
    {
     "id": "group-theory",
     "hits": 8,
     "csir": 7,
     "gate": 1,
     "sessions": 6,
     "diff": {
      "seed": 0,
      "standard": 5,
      "apex": 3
     }
    },
    {
     "id": "special-functions",
     "hits": 7,
     "csir": 7,
     "gate": 0,
     "sessions": 6,
     "diff": {
      "seed": 0,
      "standard": 4,
      "apex": 3
     }
    },
    {
     "id": "greens-functions",
     "hits": 2,
     "csir": 2,
     "gate": 0,
     "sessions": 2,
     "diff": {
      "seed": 0,
      "standard": 0,
      "apex": 2
     }
    }
   ]
  },
  {
   "id": "classical",
   "title": "Classical Mechanics",
   "total": 145,
   "rows": [
    {
     "id": "hamiltonian",
     "hits": 33,
     "csir": 18,
     "gate": 15,
     "sessions": 17,
     "diff": {
      "seed": 7,
      "standard": 13,
      "apex": 13
     }
    },
    {
     "id": "lagrangian",
     "hits": 26,
     "csir": 14,
     "gate": 12,
     "sessions": 17,
     "diff": {
      "seed": 7,
      "standard": 9,
      "apex": 10
     }
    },
    {
     "id": "central-orbits",
     "hits": 26,
     "csir": 14,
     "gate": 12,
     "sessions": 17,
     "diff": {
      "seed": 7,
      "standard": 12,
      "apex": 7
     }
    },
    {
     "id": "relativity",
     "hits": 24,
     "csir": 15,
     "gate": 9,
     "sessions": 15,
     "diff": {
      "seed": 7,
      "standard": 12,
      "apex": 5
     }
    },
    {
     "id": "rigid-body",
     "hits": 15,
     "csir": 11,
     "gate": 4,
     "sessions": 10,
     "diff": {
      "seed": 1,
      "standard": 9,
      "apex": 5
     }
    },
    {
     "id": "small-oscillations",
     "hits": 14,
     "csir": 9,
     "gate": 5,
     "sessions": 14,
     "diff": {
      "seed": 3,
      "standard": 7,
      "apex": 4
     }
    },
    {
     "id": "canonical-pb",
     "hits": 4,
     "csir": 1,
     "gate": 3,
     "sessions": 4,
     "diff": {
      "seed": 3,
      "standard": 0,
      "apex": 1
     }
    },
    {
     "id": "fluids",
     "hits": 2,
     "csir": 2,
     "gate": 0,
     "sessions": 1,
     "diff": {
      "seed": 0,
      "standard": 0,
      "apex": 2
     }
    },
    {
     "id": "constraints",
     "hits": 1,
     "csir": 1,
     "gate": 0,
     "sessions": 1,
     "diff": {
      "seed": 0,
      "standard": 1,
      "apex": 0
     }
    }
   ]
  },
  {
   "id": "emtheory",
   "title": "Electromagnetic Theory",
   "total": 218,
   "rows": [
    {
     "id": "electrostatics",
     "hits": 75,
     "csir": 36,
     "gate": 39,
     "sessions": 23,
     "diff": {
      "seed": 28,
      "standard": 29,
      "apex": 18
     }
    },
    {
     "id": "magnetostatics",
     "hits": 63,
     "csir": 38,
     "gate": 25,
     "sessions": 23,
     "diff": {
      "seed": 15,
      "standard": 23,
      "apex": 25
     }
    },
    {
     "id": "dielectrics",
     "hits": 26,
     "csir": 11,
     "gate": 15,
     "sessions": 17,
     "diff": {
      "seed": 11,
      "standard": 11,
      "apex": 4
     }
    },
    {
     "id": "radiation",
     "hits": 19,
     "csir": 13,
     "gate": 6,
     "sessions": 13,
     "diff": {
      "seed": 4,
      "standard": 5,
      "apex": 10
     }
    },
    {
     "id": "maxwell-poynting",
     "hits": 13,
     "csir": 7,
     "gate": 6,
     "sessions": 12,
     "diff": {
      "seed": 4,
      "standard": 6,
      "apex": 3
     }
    },
    {
     "id": "waves-media",
     "hits": 8,
     "csir": 5,
     "gate": 3,
     "sessions": 7,
     "diff": {
      "seed": 3,
      "standard": 1,
      "apex": 4
     }
    },
    {
     "id": "fresnel-polarization",
     "hits": 5,
     "csir": 4,
     "gate": 1,
     "sessions": 4,
     "diff": {
      "seed": 0,
      "standard": 2,
      "apex": 3
     }
    },
    {
     "id": "boundary-value",
     "hits": 4,
     "csir": 3,
     "gate": 1,
     "sessions": 3,
     "diff": {
      "seed": 0,
      "standard": 2,
      "apex": 2
     }
    },
    {
     "id": "waveguides",
     "hits": 4,
     "csir": 4,
     "gate": 0,
     "sessions": 3,
     "diff": {
      "seed": 0,
      "standard": 0,
      "apex": 4
     }
    },
    {
     "id": "images-multipole",
     "hits": 1,
     "csir": 0,
     "gate": 1,
     "sessions": 1,
     "diff": {
      "seed": 0,
      "standard": 1,
      "apex": 0
     }
    }
   ]
  },
  {
   "id": "quantum",
   "title": "Quantum Mechanics",
   "total": 175,
   "rows": [
    {
     "id": "operators-commutators",
     "hits": 58,
     "csir": 28,
     "gate": 30,
     "sessions": 21,
     "diff": {
      "seed": 19,
      "standard": 27,
      "apex": 12
     }
    },
    {
     "id": "angular-spin",
     "hits": 40,
     "csir": 14,
     "gate": 26,
     "sessions": 20,
     "diff": {
      "seed": 21,
      "standard": 12,
      "apex": 7
     }
    },
    {
     "id": "scattering",
     "hits": 22,
     "csir": 14,
     "gate": 8,
     "sessions": 15,
     "diff": {
      "seed": 5,
      "standard": 3,
      "apex": 14
     }
    },
    {
     "id": "hydrogen-atom",
     "hits": 14,
     "csir": 5,
     "gate": 9,
     "sessions": 12,
     "diff": {
      "seed": 6,
      "standard": 4,
      "apex": 4
     }
    },
    {
     "id": "harmonic-oscillator",
     "hits": 12,
     "csir": 4,
     "gate": 8,
     "sessions": 10,
     "diff": {
      "seed": 4,
      "standard": 7,
      "apex": 1
     }
    },
    {
     "id": "wells-tunneling",
     "hits": 12,
     "csir": 5,
     "gate": 7,
     "sessions": 10,
     "diff": {
      "seed": 4,
      "standard": 5,
      "apex": 3
     }
    },
    {
     "id": "two-level",
     "hits": 5,
     "csir": 1,
     "gate": 4,
     "sessions": 5,
     "diff": {
      "seed": 4,
      "standard": 0,
      "apex": 1
     }
    },
    {
     "id": "perturbation",
     "hits": 4,
     "csir": 4,
     "gate": 0,
     "sessions": 4,
     "diff": {
      "seed": 0,
      "standard": 2,
      "apex": 2
     }
    },
    {
     "id": "variational-wkb",
     "hits": 4,
     "csir": 3,
     "gate": 1,
     "sessions": 3,
     "diff": {
      "seed": 1,
      "standard": 0,
      "apex": 3
     }
    },
    {
     "id": "identical-particles",
     "hits": 4,
     "csir": 2,
     "gate": 2,
     "sessions": 4,
     "diff": {
      "seed": 0,
      "standard": 4,
      "apex": 0
     }
    }
   ]
  },
  {
   "id": "thermo",
   "title": "Thermo & Statistical Mechanics",
   "total": 96,
   "rows": [
    {
     "id": "laws-maxwell",
     "hits": 50,
     "csir": 26,
     "gate": 24,
     "sessions": 22,
     "diff": {
      "seed": 16,
      "standard": 24,
      "apex": 10
     }
    },
    {
     "id": "quantum-stats",
     "hits": 17,
     "csir": 5,
     "gate": 12,
     "sessions": 12,
     "diff": {
      "seed": 8,
      "standard": 5,
      "apex": 4
     }
    },
    {
     "id": "phase-transitions",
     "hits": 8,
     "csir": 4,
     "gate": 4,
     "sessions": 5,
     "diff": {
      "seed": 4,
      "standard": 1,
      "apex": 3
     }
    },
    {
     "id": "engines-cycles",
     "hits": 6,
     "csir": 3,
     "gate": 3,
     "sessions": 6,
     "diff": {
      "seed": 2,
      "standard": 4,
      "apex": 0
     }
    },
    {
     "id": "ensembles-partition",
     "hits": 6,
     "csir": 3,
     "gate": 3,
     "sessions": 4,
     "diff": {
      "seed": 2,
      "standard": 4,
      "apex": 0
     }
    },
    {
     "id": "kinetic-theory",
     "hits": 3,
     "csir": 1,
     "gate": 2,
     "sessions": 3,
     "diff": {
      "seed": 1,
      "standard": 1,
      "apex": 1
     }
    },
    {
     "id": "fluctuations",
     "hits": 2,
     "csir": 2,
     "gate": 0,
     "sessions": 2,
     "diff": {
      "seed": 0,
      "standard": 1,
      "apex": 1
     }
    },
    {
     "id": "ising-critical",
     "hits": 2,
     "csir": 1,
     "gate": 1,
     "sessions": 2,
     "diff": {
      "seed": 1,
      "standard": 0,
      "apex": 1
     }
    },
    {
     "id": "blackbody",
     "hits": 1,
     "csir": 1,
     "gate": 0,
     "sessions": 1,
     "diff": {
      "seed": 0,
      "standard": 0,
      "apex": 1
     }
    },
    {
     "id": "bec",
     "hits": 1,
     "csir": 1,
     "gate": 0,
     "sessions": 1,
     "diff": {
      "seed": 0,
      "standard": 1,
      "apex": 0
     }
    }
   ]
  },
  {
   "id": "electronics",
   "title": "Electronics & Experimental",
   "total": 81,
   "rows": [
    {
     "id": "digital-logic",
     "hits": 32,
     "csir": 18,
     "gate": 14,
     "sessions": 20,
     "diff": {
      "seed": 9,
      "standard": 18,
      "apex": 5
     }
    },
    {
     "id": "bjt-fet-amplifiers",
     "hits": 21,
     "csir": 11,
     "gate": 10,
     "sessions": 13,
     "diff": {
      "seed": 7,
      "standard": 9,
      "apex": 5
     }
    },
    {
     "id": "diode-circuits",
     "hits": 15,
     "csir": 11,
     "gate": 4,
     "sessions": 13,
     "diff": {
      "seed": 3,
      "standard": 10,
      "apex": 2
     }
    },
    {
     "id": "opamp",
     "hits": 8,
     "csir": 5,
     "gate": 3,
     "sessions": 7,
     "diff": {
      "seed": 2,
      "standard": 3,
      "apex": 3
     }
    },
    {
     "id": "adc-dac",
     "hits": 3,
     "csir": 3,
     "gate": 0,
     "sessions": 3,
     "diff": {
      "seed": 0,
      "standard": 1,
      "apex": 2
     }
    },
    {
     "id": "oscillators",
     "hits": 2,
     "csir": 2,
     "gate": 0,
     "sessions": 2,
     "diff": {
      "seed": 0,
      "standard": 1,
      "apex": 1
     }
    }
   ]
  },
  {
   "id": "atomic",
   "title": "Atomic & Molecular",
   "total": 32,
   "rows": [
    {
     "id": "mol-spectra",
     "hits": 16,
     "csir": 9,
     "gate": 7,
     "sessions": 12,
     "diff": {
      "seed": 5,
      "standard": 2,
      "apex": 9
     }
    },
    {
     "id": "laser",
     "hits": 7,
     "csir": 3,
     "gate": 4,
     "sessions": 5,
     "diff": {
      "seed": 2,
      "standard": 2,
      "apex": 3
     }
    },
    {
     "id": "coupling-terms",
     "hits": 5,
     "csir": 1,
     "gate": 4,
     "sessions": 5,
     "diff": {
      "seed": 2,
      "standard": 2,
      "apex": 1
     }
    },
    {
     "id": "fine-hyperfine",
     "hits": 2,
     "csir": 1,
     "gate": 1,
     "sessions": 2,
     "diff": {
      "seed": 1,
      "standard": 0,
      "apex": 1
     }
    },
    {
     "id": "selection-rules",
     "hits": 1,
     "csir": 1,
     "gate": 0,
     "sessions": 1,
     "diff": {
      "seed": 0,
      "standard": 0,
      "apex": 1
     }
    },
    {
     "id": "nmr-esr",
     "hits": 1,
     "csir": 0,
     "gate": 1,
     "sessions": 1,
     "diff": {
      "seed": 1,
      "standard": 0,
      "apex": 0
     }
    }
   ]
  },
  {
   "id": "nuclear",
   "title": "Nuclear & Particle",
   "total": 59,
   "rows": [
    {
     "id": "conservation-quark",
     "hits": 21,
     "csir": 7,
     "gate": 14,
     "sessions": 16,
     "diff": {
      "seed": 12,
      "standard": 2,
      "apex": 7
     }
    },
    {
     "id": "decay-activity",
     "hits": 10,
     "csir": 4,
     "gate": 6,
     "sessions": 9,
     "diff": {
      "seed": 4,
      "standard": 3,
      "apex": 3
     }
    },
    {
     "id": "shell-model",
     "hits": 9,
     "csir": 4,
     "gate": 5,
     "sessions": 8,
     "diff": {
      "seed": 4,
      "standard": 1,
      "apex": 4
     }
    },
    {
     "id": "reactions-qvalue",
     "hits": 6,
     "csir": 4,
     "gate": 2,
     "sessions": 5,
     "diff": {
      "seed": 1,
      "standard": 1,
      "apex": 4
     }
    },
    {
     "id": "decay-kinematics",
     "hits": 5,
     "csir": 2,
     "gate": 3,
     "sessions": 5,
     "diff": {
      "seed": 1,
      "standard": 2,
      "apex": 2
     }
    },
    {
     "id": "semf-binding",
     "hits": 3,
     "csir": 3,
     "gate": 0,
     "sessions": 3,
     "diff": {
      "seed": 0,
      "standard": 0,
      "apex": 3
     }
    },
    {
     "id": "detectors-accelerators",
     "hits": 3,
     "csir": 1,
     "gate": 2,
     "sessions": 3,
     "diff": {
      "seed": 1,
      "standard": 1,
      "apex": 1
     }
    },
    {
     "id": "fission-fusion",
     "hits": 2,
     "csir": 2,
     "gate": 0,
     "sessions": 2,
     "diff": {
      "seed": 0,
      "standard": 0,
      "apex": 2
     }
    }
   ]
  },
  {
   "id": "solidstate",
   "title": "Solid State / Condensed Matter",
   "total": 95,
   "rows": [
    {
     "id": "crystal-structure",
     "hits": 50,
     "csir": 21,
     "gate": 29,
     "sessions": 22,
     "diff": {
      "seed": 18,
      "standard": 11,
      "apex": 21
     }
    },
    {
     "id": "phonons-specheat",
     "hits": 15,
     "csir": 8,
     "gate": 7,
     "sessions": 13,
     "diff": {
      "seed": 4,
      "standard": 4,
      "apex": 7
     }
    },
    {
     "id": "semiconductors",
     "hits": 8,
     "csir": 1,
     "gate": 7,
     "sessions": 5,
     "diff": {
      "seed": 4,
      "standard": 3,
      "apex": 1
     }
    },
    {
     "id": "magnetism",
     "hits": 8,
     "csir": 1,
     "gate": 7,
     "sessions": 5,
     "diff": {
      "seed": 4,
      "standard": 3,
      "apex": 1
     }
    },
    {
     "id": "superconductivity",
     "hits": 5,
     "csir": 2,
     "gate": 3,
     "sessions": 4,
     "diff": {
      "seed": 2,
      "standard": 1,
      "apex": 2
     }
    },
    {
     "id": "reciprocal-diffraction",
     "hits": 4,
     "csir": 0,
     "gate": 4,
     "sessions": 3,
     "diff": {
      "seed": 4,
      "standard": 0,
      "apex": 0
     }
    },
    {
     "id": "free-electron",
     "hits": 4,
     "csir": 0,
     "gate": 4,
     "sessions": 4,
     "diff": {
      "seed": 4,
      "standard": 0,
      "apex": 0
     }
    },
    {
     "id": "band-theory",
     "hits": 1,
     "csir": 0,
     "gate": 1,
     "sessions": 1,
     "diff": {
      "seed": 1,
      "standard": 0,
      "apex": 0
     }
    }
   ]
  },
  {
   "id": "aptitude",
   "title": "General Aptitude (GA / Part A)",
   "total": 213,
   "rows": [
    {
     "id": "quant-core",
     "hits": 125,
     "csir": 95,
     "gate": 30,
     "sessions": 22,
     "diff": {
      "seed": 28,
      "standard": 97,
      "apex": 0
     }
    },
    {
     "id": "spatial",
     "hits": 25,
     "csir": 17,
     "gate": 8,
     "sessions": 15,
     "diff": {
      "seed": 8,
      "standard": 17,
      "apex": 0
     }
    },
    {
     "id": "probability-combinatorics",
     "hits": 20,
     "csir": 15,
     "gate": 5,
     "sessions": 13,
     "diff": {
      "seed": 5,
      "standard": 15,
      "apex": 0
     }
    },
    {
     "id": "logical-reasoning",
     "hits": 14,
     "csir": 3,
     "gate": 11,
     "sessions": 11,
     "diff": {
      "seed": 10,
      "standard": 4,
      "apex": 0
     }
    },
    {
     "id": "verbal",
     "hits": 11,
     "csir": 0,
     "gate": 11,
     "sessions": 6,
     "diff": {
      "seed": 11,
      "standard": 0,
      "apex": 0
     }
    },
    {
     "id": "everyday-science",
     "hits": 9,
     "csir": 7,
     "gate": 2,
     "sessions": 8,
     "diff": {
      "seed": 2,
      "standard": 7,
      "apex": 0
     }
    },
    {
     "id": "data-interpretation",
     "hits": 7,
     "csir": 3,
     "gate": 4,
     "sessions": 7,
     "diff": {
      "seed": 3,
      "standard": 4,
      "apex": 0
     }
    },
    {
     "id": "series-patterns",
     "hits": 2,
     "csir": 1,
     "gate": 1,
     "sessions": 2,
     "diff": {
      "seed": 1,
      "standard": 1,
      "apex": 0
     }
    }
   ]
  }
 ],
 "drills": [
  {
   "rank": 1,
   "id": "dice-coins-probability",
   "hits": 76,
   "sessions": 22,
   "exams": "CSIR+GATE",
   "forgeId": "drill-dice-coins-probability-01"
  },
  {
   "rank": 2,
   "id": "ratio-percentage",
   "hits": 39,
   "sessions": 20,
   "exams": "CSIR+GATE",
   "forgeId": "drill-ratio-percentage-01"
  },
  {
   "rank": 3,
   "id": "harmonic-oscillator",
   "hits": 31,
   "sessions": 19,
   "exams": "CSIR+GATE",
   "forgeId": "drill-harmonic-oscillator-01"
  },
  {
   "rank": 4,
   "id": "wells-bound-states",
   "hits": 27,
   "sessions": 16,
   "exams": "CSIR+GATE",
   "forgeId": "drill-wells-bound-states-01"
  },
  {
   "rank": 5,
   "id": "clocks-calendars",
   "hits": 20,
   "sessions": 14,
   "exams": "CSIR+GATE",
   "forgeId": "drill-clocks-calendars-01"
  },
  {
   "rank": 6,
   "id": "series-completion",
   "hits": 18,
   "sessions": 13,
   "exams": "CSIR+GATE",
   "forgeId": "drill-series-completion-01"
  },
  {
   "rank": 7,
   "id": "partition-function-two-level",
   "hits": 16,
   "sessions": 13,
   "exams": "CSIR+GATE",
   "forgeId": "drill-partition-function-two-level-01"
  },
  {
   "rank": 8,
   "id": "scattering-cross-section",
   "hits": 15,
   "sessions": 13,
   "exams": "CSIR+GATE",
   "forgeId": "drill-scattering-cross-section-01"
  },
  {
   "rank": 9,
   "id": "opamp-golden-rules",
   "hits": 13,
   "sessions": 11,
   "exams": "CSIR+GATE",
   "forgeId": "drill-opamp-golden-rules-01"
  },
  {
   "rank": 10,
   "id": "flipflop-counters",
   "hits": 16,
   "sessions": 10,
   "exams": "CSIR+GATE",
   "forgeId": "drill-flipflop-counters-01"
  },
  {
   "rank": 11,
   "id": "contour-residues",
   "hits": 12,
   "sessions": 10,
   "exams": "CSIR+GATE",
   "forgeId": "drill-contour-residues-01"
  },
  {
   "rank": 12,
   "id": "debye-t3",
   "hits": 11,
   "sessions": 10,
   "exams": "CSIR+GATE",
   "forgeId": "drill-debye-t3-01"
  },
  {
   "rank": 13,
   "id": "perturbation-theory",
   "hits": 10,
   "sessions": 10,
   "exams": "CSIR+GATE",
   "forgeId": "drill-perturbation-theory-01"
  },
  {
   "rank": 14,
   "id": "band-effective-mass",
   "hits": 13,
   "sessions": 9,
   "exams": "CSIR+GATE",
   "forgeId": "drill-band-effective-mass-01"
  },
  {
   "rank": 15,
   "id": "bragg-laue-diffraction",
   "hits": 7,
   "sessions": 6,
   "exams": "CSIR+GATE",
   "forgeId": "drill-bragg-laue-diffraction-01"
  },
  {
   "rank": 16,
   "id": "normal-modes",
   "hits": 6,
   "sessions": 6,
   "exams": "CSIR+GATE",
   "forgeId": "drill-normal-modes-01"
  },
  {
   "rank": 17,
   "id": "commutator-identities",
   "hits": 6,
   "sessions": 6,
   "exams": "CSIR+GATE",
   "forgeId": "drill-commutator-identities-01"
  },
  {
   "rank": 18,
   "id": "zeeman-patterns",
   "hits": 7,
   "sessions": 5,
   "exams": "CSIR+GATE",
   "forgeId": "drill-zeeman-patterns-01"
  },
  {
   "rank": 19,
   "id": "radioactive-decay",
   "hits": 5,
   "sessions": 5,
   "exams": "CSIR+GATE",
   "forgeId": "drill-radioactive-decay-01"
  },
  {
   "rank": 20,
   "id": "hall-effect",
   "hits": 5,
   "sessions": 5,
   "exams": "CSIR+GATE",
   "forgeId": "drill-hall-effect-01"
  },
  {
   "rank": 21,
   "id": "pn-junction-diode",
   "hits": 5,
   "sessions": 4,
   "exams": "CSIR+GATE",
   "forgeId": "drill-pn-junction-diode-01"
  },
  {
   "rank": 22,
   "id": "group-vs-phase-velocity",
   "hits": 4,
   "sessions": 4,
   "exams": "CSIR+GATE",
   "forgeId": "drill-group-vs-phase-velocity-01"
  },
  {
   "rank": 23,
   "id": "hydrogen-spectra",
   "hits": 4,
   "sessions": 4,
   "exams": "CSIR+GATE",
   "forgeId": "drill-hydrogen-spectra-01"
  },
  {
   "rank": 24,
   "id": "data-graphs",
   "hits": 4,
   "sessions": 4,
   "exams": "CSIR+GATE",
   "forgeId": "drill-data-graphs-01"
  },
  {
   "rank": 25,
   "id": "carnot-cycles",
   "hits": 4,
   "sessions": 3,
   "exams": "CSIR+GATE",
   "forgeId": "drill-carnot-cycles-01"
  },
  {
   "rank": 26,
   "id": "digital-counters",
   "hits": 4,
   "sessions": 3,
   "exams": "CSIR+GATE",
   "forgeId": "drill-digital-counters-01"
  },
  {
   "rank": 27,
   "id": "semf-fission",
   "hits": 3,
   "sessions": 3,
   "exams": "CSIR+GATE",
   "forgeId": "drill-semf-fission-01"
  },
  {
   "rank": 28,
   "id": "entropy-calculations",
   "hits": 3,
   "sessions": 3,
   "exams": "CSIR+GATE",
   "forgeId": "drill-entropy-calculations-01"
  }
 ],
 "unclassified": {
  "csir": [
   "dec2025 Q3 (A)",
   "dec2025 Q6 (A)",
   "dec2025 Q9 (A)",
   "dec2025 Q12 (A)",
   "dec2025 Q15 (A)",
   "dec2025 Q19 (A)",
   "dec2025 Q27 (B)",
   "dec2025 Q28 (B)",
   "dec2025 Q31 (B)",
   "dec2025 Q34 (B)",
   "dec2025 Q42 (B)",
   "dec2025 Q44 (B)",
   "dec2025 Q45 (B)",
   "dec2025 Q66 (C)",
   "dec2025 Q67 (C)",
   "dec2025 Q68 (C)",
   "jun2021 Q2 (A)",
   "jun2021 Q3 (A)",
   "jun2021 Q4 (A)",
   "jun2021 Q9 (A)",
   "jun2021 Q13 (A)",
   "jun2021 Q17 (A)",
   "jun2021 Q18 (A)",
   "jun2021 Q24 (B)",
   "jun2021 Q26 (B)",
   "jun2021 Q28 (B)",
   "jun2021 Q30 (B)",
   "jun2021 Q39 (B)",
   "jun2021 Q46 (C)",
   "jun2021 Q48 (C)",
   "jun2021 Q55 (C)",
   "jun2021 Q62 (C)",
   "jul2025 Q1 (A)",
   "jul2025 Q3 (A)",
   "jul2025 Q11 (A)",
   "jul2025 Q12 (A)",
   "jul2025 Q16 (A)",
   "jul2025 Q20 (A)",
   "jul2025 Q24 (B)",
   "jul2025 Q25 (B)",
   "jul2025 Q26 (B)",
   "jul2025 Q34 (B)",
   "jul2025 Q38 (B)",
   "jul2025 Q42 (B)",
   "jul2025 Q45 (B)",
   "jul2025 Q46 (C)",
   "jul2025 Q47 (C)",
   "jul2025 Q52 (C)",
   "jul2025 Q65 (C)",
   "dec2019 Q8 (A)",
   "dec2019 Q10 (A)",
   "dec2019 Q13 (A)",
   "dec2019 Q14 (A)",
   "dec2019 Q22 (B)",
   "dec2019 Q24 (B)",
   "dec2019 Q27 (B)",
   "dec2019 Q30 (B)",
   "dec2019 Q45 (C)",
   "dec2019 Q49 (C)",
   "dec2019 Q54 (C)",
   "dec2019 Q58 (C)",
   "dec2019 Q59 (C)",
   "dec2019 Q64 (C)",
   "dec2019 Q65 (C)",
   "dec2019 Q67 (C)",
   "dec2019 Q73 (C)",
   "june2018 Q4 (A)",
   "june2018 Q5 (A)",
   "june2018 Q6 (A)",
   "june2018 Q9 (A)",
   "june2018 Q10 (A)",
   "june2018 Q13 (A)",
   "june2018 Q15 (A)",
   "june2018 Q16 (A)",
   "june2018 Q17 (A)",
   "june2018 Q18 (A)",
   "june2018 Q19 (A)",
   "june2018 Q24 (B)",
   "june2018 Q25 (B)",
   "june2018 Q27 (B)",
   "june2018 Q28 (B)",
   "june2018 Q31 (B)",
   "june2018 Q43 (B)",
   "june2018 Q51 (C)",
   "june2018 Q53 (C)",
   "june2018 Q59 (C)",
   "june2018 Q63 (C)",
   "june2018 Q66 (C)",
   "june2018 Q70 (C)",
   "dec2024 Q22 (B)",
   "dec2024 Q30 (B)",
   "dec2024 Q31 (B)",
   "dec2024 Q34 (B)",
   "dec2024 Q41 (B)",
   "dec2024 Q46 (C)",
   "dec2024 Q49 (C)",
   "dec2024 Q52 (C)",
   "dec2024 Q58 (C)",
   "dec2024 Q69 (C)",
   "dec2024 Q71 (C)",
   "dec2024 Q73 (C)",
   "dec2024 Q30 (B)",
   "dec2024 Q31 (B)",
   "dec2024 Q34 (B)",
   "dec2024 Q41 (B)",
   "dec2024 Q46 (C)",
   "dec2024 Q49 (C)",
   "dec2024 Q52 (C)",
   "dec2024 Q58 (C)",
   "dec2024 Q69 (C)",
   "dec2024 Q71 (C)",
   "dec2024 Q73 (C)",
   "dec2018 Q3 (A)",
   "dec2018 Q4 (A)",
   "dec2018 Q5 (A)",
   "dec2018 Q9 (A)",
   "dec2018 Q10 (A)",
   "dec2018 Q11 (A)",
   "dec2018 Q12 (A)",
   "dec2018 Q17 (A)",
   "dec2018 Q18 (A)",
   "dec2018 Q19 (A)",
   "dec2018 Q20 (A)",
   "dec2018 Q24 (B)",
   "dec2018 Q44 (B)",
   "dec2018 Q49 (C)",
   "dec2018 Q64 (C)",
   "dec2018 Q65 (C)",
   "dec2018 Q67 (C)",
   "dec2018 Q69 (C)",
   "dec2023 Q1 (A)",
   "dec2023 Q3 (A)",
   "dec2023 Q4 (A)",
   "dec2023 Q5 (A)",
   "dec2023 Q8 (A)",
   "dec2023 Q9 (A)",
   "dec2023 Q13 (A)",
   "dec2023 Q14 (A)",
   "dec2023 Q18 (A)",
   "dec2023 Q19 (A)",
   "dec2023 Q21 (B)",
   "dec2023 Q31 (B)",
   "dec2023 Q42 (B)",
   "dec2023 Q58 (C)",
   "june2023 Q8 (A)",
   "june2023 Q15 (A)",
   "june2023 Q18 (A)",
   "june2023 Q30 (B)",
   "june2023 Q37 (B)",
   "june2023 Q39 (B)",
   "june2023 Q44 (B)",
   "june2023 Q45 (B)",
   "june2023 Q48 (C)",
   "june2023 Q51 (C)",
   "june2023 Q54 (C)",
   "june2023 Q59 (C)",
   "june2023 Q70 (C)",
   "june2023 Q73 (C)",
   "june2023 Q74 (C)",
   "sep2022 Q2 (A)",
   "sep2022 Q3 (A)",
   "sep2022 Q5 (A)",
   "sep2022 Q12 (A)",
   "sep2022 Q13 (A)",
   "sep2022 Q14 (A)",
   "sep2022 Q15 (A)",
   "sep2022 Q17 (A)",
   "sep2022 Q23 (B)",
   "sep2022 Q26 (B)",
   "sep2022 Q33 (B)",
   "sep2022 Q41 (B)",
   "sep2022 Q44 (B)",
   "sep2022 Q51 (C)",
   "sep2022 Q59 (C)",
   "june2020 Q1 (A)",
   "june2020 Q3 (A)",
   "june2020 Q4 (A)",
   "june2020 Q6 (A)",
   "june2020 Q9 (A)",
   "june2020 Q11 (A)",
   "june2020 Q14 (A)",
   "june2020 Q18 (A)",
   "june2020 Q21 (B)",
   "june2020 Q28 (B)",
   "june2020 Q30 (B)",
   "june2020 Q34 (B)",
   "june2020 Q35 (B)",
   "june2020 Q39 (B)",
   "june2020 Q41 (B)",
   "june2020 Q50 (C)",
   "june2020 Q63 (C)",
   "june2020 Q69 (C)",
   "june2020 Q71 (C)",
   "june2024 Q5 (A)",
   "june2024 Q6 (A)",
   "june2024 Q9 (A)",
   "june2024 Q12 (A)",
   "june2024 Q13 (A)",
   "june2024 Q20 (A)",
   "june2024 Q25 (B)",
   "june2024 Q27 (B)",
   "june2024 Q28 (B)",
   "june2024 Q36 (B)",
   "june2024 Q42 (B)",
   "june2024 Q43 (B)",
   "june2024 Q52 (C)",
   "june2024 Q56 (C)",
   "june2024 Q60 (C)",
   "june2024 Q64 (C)",
   "june2024 Q74 (C)"
  ],
  "gate": [
   "gate2016 Q1 (A)",
   "gate2016 Q2 (A)",
   "gate2016 Q5 (A)",
   "gate2016 Q7 (B)",
   "gate2016 Q8 (B)",
   "gate2016 Q13 (C)",
   "gate2016 Q19 (C)",
   "gate2016 Q26 (C)",
   "gate2016 Q28 (C)",
   "gate2016 Q30 (C)",
   "gate2016 Q35 (C)",
   "gate2016 Q44 (D)",
   "gate2016 Q51 (D)",
   "gate2024 Q1 (A)",
   "gate2024 Q4 (A)",
   "gate2024 Q10 (A)",
   "gate2024 Q24 (B)",
   "gate2024 Q25 (B)",
   "gate2024 Q26 (B)",
   "gate2024 Q29 (B)",
   "gate2024 Q30 (B)",
   "gate2024 Q51 (C)",
   "gate2025 Q9 (A)",
   "gate2025 Q13 (B)",
   "gate2025 Q32 (B)",
   "gate2025 Q55 (C)",
   "gate2020 Q1 (A)",
   "gate2020 Q2 (A)",
   "gate2020 Q5 (A)",
   "gate2020 Q8 (A)",
   "gate2020 Q11 (B)",
   "gate2020 Q13 (B)",
   "gate2020 Q22 (B)",
   "gate2020 Q35 (B)",
   "gate2020 Q39 (C)",
   "gate2020 Q58 (C)",
   "gate2020 Q59 (C)",
   "gate2020 Q65 (C)",
   "gate2017 Q5 (B)",
   "gate2017 Q6 (B)",
   "gate2017 Q7 (B)",
   "gate2017 Q16 (B)",
   "gate2017 Q18 (B)",
   "gate2017 Q21 (B)",
   "gate2017 Q28 (B)",
   "gate2017 Q37 (B)",
   "gate2017 Q41 (B)",
   "gate2017 Q56 (A)",
   "gate2017 Q57 (A)",
   "gate2017 Q58 (A)",
   "gate2017 Q61 (A)",
   "gate2017 Q62 (A)",
   "gate2017 Q63 (A)",
   "gate2018 Q3 (A)",
   "gate2018 Q4 (A)",
   "gate2018 Q7 (A)",
   "gate2018 Q8 (A)",
   "gate2018 Q9 (A)",
   "gate2018 Q14 (B)",
   "gate2018 Q15 (B)",
   "gate2018 Q19 (B)",
   "gate2018 Q28 (B)",
   "gate2018 Q29 (B)",
   "gate2018 Q31 (B)",
   "gate2018 Q35 (B)",
   "gate2018 Q36 (B)",
   "gate2018 Q37 (B)",
   "gate2018 Q53 (B)",
   "gate2018 Q55 (B)",
   "gate2018 Q56 (B)",
   "gate2018 Q61 (B)",
   "gate2019 Q1 (A)",
   "gate2019 Q5 (A)",
   "gate2019 Q11 (B)",
   "gate2019 Q13 (B)",
   "gate2019 Q37 (B)",
   "gate2019 Q39 (B)",
   "gate2019 Q53 (B)",
   "gate2019 Q55 (B)",
   "gate2019 Q56 (B)",
   "gate2019 Q57 (B)",
   "gate2019 Q64 (B)",
   "gate2021 Q10 (A)",
   "gate2021 Q12 (B)",
   "gate2021 Q28 (B)",
   "gate2021 Q35 (B)",
   "gate2021 Q42 (B)",
   "gate2022 Q1 (A)",
   "gate2022 Q2 (A)",
   "gate2022 Q4 (A)",
   "gate2022 Q5 (A)",
   "gate2022 Q30 (B)",
   "gate2022 Q38 (B)",
   "gate2022 Q39 (B)",
   "gate2022 Q41 (B)",
   "gate2022 Q48 (B)",
   "gate2023 Q32 (B)",
   "gate2023 Q42 (B)",
   "gate2023 Q50 (B)",
   "gate2023 Q28 (B)",
   "gate2023 Q27 (B)",
   "gate2023 Q44 (B)",
   "gate2026 Q2 (A)",
   "gate2026 Q9 (A)",
   "gate2026 Q14 (B)",
   "gate2026 Q16 (B)",
   "gate2026 Q21 (B)",
   "gate2026 Q22 (B)",
   "gate2026 Q23 (B)",
   "gate2026 Q27 (B)",
   "gate2026 Q28 (B)",
   "gate2026 Q35 (B)",
   "gate2026 Q36 (B)",
   "gate2026 Q44 (B)",
   "gate2026 Q49 (B)"
  ]
 },
 "emptySubs": [
  "electronics/experimental-methods",
  "atomic/zeeman-stark"
 ]
};
